(PC-3668): Ajout du VenueType "Offre Numerique" sur les venues digitales par défaut
pass-culture/pass-culture-api pull request #1396
Opened 2020-09-07 15:33 UTC by floragc-octo

Sur celles qui sont crées par defaut a la creation d'une structure ou compte pro

2020-09-08 08:35 UTC, DanielBaudry commented on models/venue_sql_entity.py
> +def _get_offre_numerique_venue_type_id() -> int:
On code en français ? :)

2020-09-08 08:35 UTC, DanielBaudry commented on models/venue_sql_entity.py
> +    return VenueType.query.filter_by(label="Offre numérique").first().id
tu peux jouer avec la relationship venueType et ne pas récupérer l'id :
digital_venue.venueType = _get_digital_offer_venue_type()

2020-09-08 08:35 UTC, DanielBaudry commented on tests/routes/post_offerer_test.py
> +from tests.model_creators.generic_creators import create_user, create_offerer, create_user_offerer, create_venue_type
Ajouter un check dans un test pour vérifier que venue_type est renseigné sur la venue ?

2020-09-08 08:35 UTC, DanielBaudry commented on tests/routes/signup_pro_test.py
> +from tests.model_creators.generic_creators import create_user, create_user_offerer, create_venue_type
Ajouter un check dans un test pour vérifier que venue_type est renseigné sur la venue ?

2020-09-08 09:04 UTC, floragc-octo commented on tests/routes/post_offerer_test.py
> +from tests.model_creators.generic_creators import create_user, create_offerer, create_user_offerer, create_venue_type
habile

2020-09-10 08:12 UTC, victorenaud requested changes
Rajouter l'obligation de mettre un type de lieu dans l'API

2020-09-10 08:12 UTC, victorenaud commented on models/venue_sql_entity.py
> +def _get_offre_numerique_venue_type_id() -> int:
Point à ajouter à la réunion standard si on veut pérenniser

2020-09-10 08:12 UTC, victorenaud commented on models/venue_sql_entity.py
>      digital_venue = VenueSQLEntity()
Renommer en français ici aussi alors ? :)

2020-09-10 08:12 UTC, victorenaud commented on models/venue_sql_entity.py
> +    return VenueType.query.filter_by(label="Offre numérique").first().id
Ce retour n'a pas été pris en compte ?

2020-09-10 08:12 UTC, victorenaud commented on tests/routes/post_offerer_test.py
> +            venue_type = create_venue_type(label="Offre numérique")
```suggestion
            digital_venue_type = create_venue_type(label="Offre numérique")
```

2020-09-10 08:12 UTC, victorenaud commented on tests/routes/post_offerer_test.py
> +            venue_type = create_venue_type(label = "Offre numérique")
Vu qu'il y en a besoin partout, ce ne serait pas mieux dans un beforeEach ?

2020-09-10 08:12 UTC, victorenaud commented on tests/routes/signup_pro_test.py
> +            venue_type = create_venue_type(label="Offre numérique")
```suggestion
            digital_venue_type = create_venue_type(label="Offre numérique")
```

2020-09-10 08:12 UTC, victorenaud commented on tests/routes/signup_pro_test.py
> +            venue_type = create_venue_type(label="Offre numérique")
Vu qu'il y en a besoin partout, ce ne serait pas mieux dans un beforeEach ?

2020-09-10 08:12 UTC, victorenaud commented on tests/scripts/offerer/file_import_test.py
> +        venue_type = create_venue_type(label="Offre numérique")
```suggestion
        digital_venue_type = create_venue_type(label="Offre numérique")
```

2020-09-10 12:57 UTC, floragc-octo commented on models/venue_sql_entity.py
>      digital_venue = VenueSQLEntity()
La remarque de Daniel, c'était justement de ne pas mettre de français mais oui je vais l'ajouter en point à évoquer au point standard :)

2020-09-10 12:58 UTC, floragc-octo commented on models/venue_sql_entity.py
> +    return VenueType.query.filter_by(label="Offre numérique").first().id
Non il n'est pas applicable sur ce model (il faudrait une relationship et on n'a qu'une clé secondaire)

2020-09-10 17:44 UTC, victorenaud approved these changes

2020-09-11 14:03 UTC, merged