(PC-4233) Activate reCaptcha challenge for ID CHECK
pass-culture/pass-culture-api pull request #1468
Opened 2020-10-13 16:10 UTC by francois-seguin

https://passculture.atlassian.net/browse/PC-4233

2020-10-14 12:05 UTC, apibrac requested changes

2020-10-14 12:05 UTC, apibrac commented on tests/connectors/api_recaptcha_test.py
> +]
Tout ça ça sert que au test suivant ?
ça se fait de le définir au premier niveau hors de la fonction de test ?

Pour l'instant je crois pas qu'on ait cette pratique, si tu pense que c'est bien ça vaudrait le coup d'en discuter avec le reste de la team

2020-10-14 12:05 UTC, apibrac commented on src/pcapi/connectors/api_recaptcha.py
> +            raise ReCaptchaException(f"reCAPTCHA score was {score} but {RECAPTCHA_REQUIRED_SCORE} is required")
Est ce qu'on a envie de raise dans ce cas là ?
Il s'agit par exemple d'un robot qui tente l'action, est ce qu'on veut carrément que l'api crash et qu'on ait les logs de notre côté ou plutôt continuer normalement en l'orientant vers une réponse "tu es un robot" ?

Je crois que la route est déjà prêt à recevoir False comme valeur pour justement refuser un token sans pour autant raise une erreur non catchée

2020-10-14 12:43 UTC, francois-seguin commented on tests/connectors/api_recaptcha_test.py
> +]
Ces variables sont en effet utilisées dans le test paramétrique suivant, qui me permet de factoriser une succession de tests autrement identiques.
J'en discute avec les collègues.

2020-10-14 13:28 UTC, francois-seguin commented on tests/connectors/api_recaptcha_test.py
> +]
(discuté en réunion sur les standards, validé par les collègues)

2020-10-14 13:29 UTC, xordoquy commented on src/pcapi/connectors/api_recaptcha.py
> +        score = json_response.get('score', 0)
On est sur d'avoir le score dans les réponses sur l'ensemble des environnements ?

2020-10-14 13:29 UTC, xordoquy commented on src/pcapi/connectors/api_recaptcha.py
> +    if json_response["success"]:
C'est garanti que l'on ait `success` ?

2020-10-14 13:29 UTC, xordoquy commented on src/pcapi/domain/beneficiary/beneficiary_licence.py
> +    return validate_recaptcha_token(token, 'submit')
Y a-t-il une possibilité que le `submit` coté id check change ?

2020-10-14 13:29 UTC, xordoquy commented on tests/connectors/api_recaptcha_test.py
> +]
Peut-être est-ce que ce serait plus lisible en déplaçant ces définitions de variables en début de fichier.

2020-10-14 13:35 UTC, francois-seguin commented on src/pcapi/connectors/api_recaptcha.py
> +    if json_response["success"]:
Oui, c'est le seul paramètre qui est toujours retourné par l'API de Google (dans une réponse de statut 200).

2020-10-14 13:39 UTC, francois-seguin commented on src/pcapi/domain/beneficiary/beneficiary_licence.py
> +    return validate_recaptcha_token(token, 'submit')
'submit' est l'action que nous définissons dans le [formulaire côté webapp](https://github.com/pass-culture/pass-culture-browser/blob/760684160bea9fac19ff25ba2eb61c9ef1d58eb6/src/components/pages/create-account/utils/recaptcha.js#L21), c'est indépendant de l'API du prestataire ID Check.

2020-10-14 16:12 UTC, apibrac approved these changes

2020-10-15 07:23 UTC, francois-seguin commented on tests/connectors/api_recaptcha_test.py
> +@pytest.mark.parametrize("response_return_value,expected_result", test_valid_response_from_api_data.values(), ids=test_valid_response_from_api_data.keys())
Suite à une remarque d'un collègue, je passe désormais l'argument `id` à `parametrize()`, afin d'améliorer leur reconnaissance dans l'output de `pytest`:
Avant:
`tests/connectors/api_recaptcha_test.py::test_valid_response_from_api[response_return_value0-True]`
Après:
`tests/connectors/api_recaptcha_test.py::test_valid_response_from_api[high_score]`

2020-10-15 09:16 UTC, xordoquy approved these changes

2020-10-15 13:12 UTC, merged