Fix validation for cancelling a stock
pass-culture/pass-culture-api pull request #1475
Opened 2020-10-15 14:26 UTC by cgaunet

2020-10-16 08:41 UTC, victorenaud requested changes

2020-10-16 08:41 UTC, victorenaud commented on src/pcapi/routes/stocks.py
> +    check_stock_is_not_imported(stock)
Je pense qu'ici tu introduis un nouveau bug qui est qu'on peut supprimer les événements qui sont terminés depuis PLUS que 48h.

Hors passé ce délai, ils sont automatiquement validé et remboursé, donc plus annulable.

2020-10-16 08:41 UTC, victorenaud commented on src/pcapi/validation/routes/stocks.py
> -    if stock.isEventExpired:
En fait il faudrait plutôt remplacer l'appel à `stock.isEventExpired` qui vérifie si l'événement est dans le passé par `stock.isEventDeletable` qui vise justement à savoir si l'événement est terminé depuis moins de 48h

2020-10-16 09:21 UTC, victorenaud commented
D'ailleurs le numéro de ticket n'apparait pas dans le commit
On a pour coutume de faire `(PC-XXX): ` devant le nom du commit
Ça permet notamment de pouvoir retrouver plus facilement les tickets jira lorsqu'on regarde l'historique (ça m'a bien servi cette semaine quand j'étais shérif ^^" )

2020-10-16 09:24 UTC, victorenaud commented on src/pcapi/routes/stocks.py
> +    check_stock_is_not_imported(stock)
En fait il faudrait plutôt remplacer l'appel à stock.isEventExpired qui vérifie si l'événement est dans le passé par stock.isEventDeletable qui vise justement à savoir si l'événement est terminé depuis moins de 48h

2020-10-16 09:24 UTC, victorenaud commented on src/pcapi/validation/routes/stocks.py
> -    if stock.isEventExpired:
En fait pour `isUpdatable` c'est bien `isEventExpired` qu'il nous faut

2020-10-16 12:20 UTC, cgaunet commented
> D'ailleurs le numéro de ticket n'apparait pas dans le commit
> On a pour coutume de faire `(PC-XXX): ` devant le nom du commit
> Ça permet notamment de pouvoir retrouver plus facilement les tickets jira lorsqu'on regarde l'historique (ça m'a bien servi cette semaine quand j'étais shérif ^^" )

J'avais demandé par rapport au standard de naming de commit, je n'ai pas eu ce retour, mais c'est noté :)

2020-10-16 12:22 UTC, cgaunet commented on src/pcapi/routes/stocks.py
> +    check_stock_is_not_imported(stock)
Mmh, non, c'est géré directement dans `delete_stock_and_cancel_bookings` ;)
C'est bien pour ça que le test `when_stock_is_an_event_that_ended_more_than_two_days_ago` renvoie toujours une 400, j'ai fait attention

2020-10-16 14:07 UTC, victorenaud commented on src/pcapi/routes/stocks.py
> +    check_stock_is_not_imported(stock)
C'est bizarre d'avoir des validations à deux endroits différents
En plus je me rend compte que le `check_stock_is_not_imported` est fait **après** le `delete_stock_and_cancel_bookings`, ce qui est un peu tard...

Du coup je déporterai `check_stock_is_not_imported` dans `domain/stocks` avec les autres validation métier.

Qu'en penses-tu ?

2020-10-19 13:23 UTC, victorenaud approved these changes

2020-10-19 13:25 UTC, merged