Pc 4808/deploy cloudrun
pass-culture/pass-culture-api pull request #1526
Opened 2020-11-03 11:35 UTC by achapusot-pass

2020-11-03 11:46 UTC, CamilSadiki requested changes
Stylé :+1:

2020-11-03 11:46 UTC, CamilSadiki commented on .circleci/config.yml
> +          #       - migration-gcp
```suggestion
      - deploy-cloudrun
          filters:
            branches:
              only:
                - migration-gcp
```

2020-11-03 11:46 UTC, CamilSadiki commented on .circleci/config.yml
> +            gcloud -q auth activate-service-account --key-file gcloud_keys
J'ai créé une commande authenticate_gcp, tu peux essayer de la reutiliser ?

2020-11-03 11:46 UTC, CamilSadiki commented on .circleci/config.yml
> +      GCP_REGISTRY_NAME: pass-culture-artifact-registry
Essayer de factoriser ces parametres. Voir si c'est possible de les declarer globalement dans config.yaml, sinon les mettre dans les env vars du projet via l'UI Circle

2020-11-03 13:05 UTC, achapusot-pass commented on .circleci/config.yml
> +            gcloud -q auth activate-service-account --key-file gcloud_keys
J'ai essayé, mais tu fixes les creds comme provenant de ${GOOGLE_AUTH} qui sont pas les même que les miens...

2020-11-03 13:08 UTC, achapusot-pass commented on .circleci/config.yml
> +      GCP_REGISTRY_NAME: pass-culture-artifact-registry
Possible de les mettre dans CircleCI...

2020-11-03 13:08 UTC, achapusot-pass commented on .circleci/config.yml
> +      GCP_REGISTRY_NAME: pass-culture-artifact-registry
Via Circle je pense

2020-11-04 14:40 UTC, CamilSadiki requested changes
LGTM, avec 2 remarques:
- Tu peux decommenter la partie workflow circle pour que le job tourne uniquement sur la branche migration-gcp ou expliquer pourquoi tu le fais pas
- Squash les commits pour pas qu'on garde des commits de debug

2020-11-04 14:40 UTC, CamilSadiki commented on .circleci/config.yml
> +          #       - migration-gcp
Tu peux commenter pourquoi tu rejettes la proposition ?

2020-11-05 08:44 UTC, CamilSadiki approved these changes
LGTM

2020-11-05 16:23 UTC, merged