(PC-4353) Add assertion on jwt secret key presence
pass-culture/pass-culture-api pull request #1563
Opened 2020-11-10 16:02 UTC by viconnex

2020-11-12 08:38 UTC, dbaty commented on src/pcapi/flask_app.py
> +assert jwt_secret_key and len(jwt_secret_key), "JWT_SECRET_KEY not found in env"
Je pense qu'on peut supprimer `len(jwt_secret_key)`, car le test d'une chaîne vide est déjà fait par la 1ère partie de l'assert (`jwt_secret_key`).

2020-11-12 13:49 UTC, xordoquy requested changes

2020-11-12 13:49 UTC, xordoquy commented on src/pcapi/flask_app.py
> +assert jwt_secret_key and len(jwt_secret_key), "JWT_SECRET_KEY not found in env"
Je me demande si on n'aurait pas moyen d'ajouter un log error pour que ça remonte aussi dans sentry ?

2020-11-13 10:32 UTC, xordoquy approved these changes

2020-11-13 10:34 UTC, merged