(Pc-6174) Add expenses in /me route
pass-culture/pass-culture-api pull request #1835
Opened 2021-01-08 16:14 UTC by viconnex

2021-01-11 11:02 UTC, xordoquy requested changes
Une objection forte et une remarque.
Pour l'objection: utiliser un float pour les prix, ça me semble source de problèmes potentiels surtout que l'on ne contrôle pas la précision du float dans la description du model.
La remarque: `VOID_FIRST_NAME` est ambiguë de part le fait que ce ne soit pas un singleton spécifique mais un simple alias vers `""`. Du coup, je ne vois pas la valeur ajoutée de cette constante.

2021-01-11 13:06 UTC, viconnex commented
> Une objection forte et une remarque.
> Pour l'objection: utiliser un float pour les prix, ça me semble source de problèmes potentiels surtout que l'on ne contrôle pas la précision du float dans la description du model.
> La remarque: `VOID_FIRST_NAME` est ambiguë de part le fait que ce ne soit pas un singleton spécifique mais un simple alias vers `""`. Du coup, je ne vois pas la valeur ajoutée de cette constante.

VOID_FIRST_NAME permet de ne pas dupliquer ce "valeur par défaut" qu'est `""`, et de savoir d'où cela vient : quand tu lis le code de "account.py", tu comprends directement à quoi cela fait référence.

2021-01-12 17:33 UTC, xordoquy reviewed
Il faudrait voir ce qu'en pense également @dbaty

2021-01-12 17:33 UTC, xordoquy commented on src/pcapi/core/users/models.py
> +        capped_digital_bookings = [booking for booking in bookings if config.digital_cap_applies(booking.stock.offer)]
```suggestion
        capped_digital_bookings_total = sum([booking.total_amount for booking in bookings if config.digital_cap_applies(booking.stock.offer)])
```

2021-01-12 17:33 UTC, xordoquy commented on src/pcapi/core/users/models.py
> +    def get_expenses(self, is_cent_amount=False):
C'est dommage d'avoir des problématiques de serialisation ici 😢 
On ne peut pas garder le Decimal jusqu'au pydantic et faire la conversion lors de la serialization ?

2021-01-13 09:08 UTC, dbaty commented on src/pcapi/core/users/models.py
> +    def get_expenses(self, is_cent_amount=False):
Même remarque que Xavier. (Et on déplace de la logique dans le modèle, je ne suis pas fan.)

2021-01-13 17:15 UTC, xordoquy approved these changes

2021-01-13 17:15 UTC, xordoquy commented on src/pcapi/core/users/models.py
> +    max: Union[Decimal, int]
```suggestion
    max: Decimal
```

2021-01-13 17:15 UTC, xordoquy commented on src/pcapi/core/users/models.py
> +    current: Union[Decimal, int]
Du coup, je pense que l'on peut:

```suggestion
    current: Decimal
```

2021-01-13 17:15 UTC, xordoquy commented on src/pcapi/routes/native/v1/serialization/account.py
> +    _convert_max = validator("max", pre=True, allow_reuse=True)(convert_to_cent)
👍

2021-01-14 09:32 UTC, merged