(PC-4353) Prevent under age user to create an account
pass-culture/pass-culture-api pull request #1842
Opened 2021-01-11 16:38 UTC by viconnex

2021-01-11 20:05 UTC, xordoquy requested changes

2021-01-11 20:05 UTC, xordoquy commented on src/pcapi/routes/native/v1/account.py
> +        raise ApiErrors({"birthdate": "The birthdate is invalid"})
```suggestion
        raise ApiErrors({"dateOfBirth": "The birthdate is invalid"})
```

2021-01-11 20:05 UTC, xordoquy commented on src/pcapi/core/users/api.py
> +        dateOfBirth=datetime.combine(birthdate, datetime.min.time()),
```suggestion
        dateOfBirth=birthdate,
```

2021-01-12 08:47 UTC, xordoquy commented on src/pcapi/core/users/api.py
> +        dateOfBirth=datetime.combine(birthdate, datetime.min.time()),
ok, donc SQLAlchemy ne fait pas le typage tout seul 🙄

2021-01-12 09:08 UTC, viconnex commented on src/pcapi/core/users/api.py
> +        dateOfBirth=datetime.combine(birthdate, datetime.min.time()),
Le but de ce changement c’est de convertir “birthdate” qui est une date en une datetime (la colonne en bdd est une datetime).
Sans ça, plus bas dans user.calculate_age() il y a un erreur “datetime.date has no method date” (à cause de la ligne relativedelta(date.today(), self.dateOfBirth.date()).years.)

2021-01-12 09:16 UTC, xordoquy approved these changes

2021-01-12 09:17 UTC, merged