(PC-6415): Add deposit version in beneficiary creation form
pass-culture/pass-culture-api pull request #1894
Opened 2021-01-22 17:48 UTC by Akhilian

2021-01-25 08:09 UTC, dbaty requested changes
Je ne suis pas très à l'aise avec cette fonctionnalité sur la prod. Ça me semble dangereux, car on risque de créer des utilisateurs avec des seuils qui ne correspondent plus à la valeur par défaut en cours. Je proposerais plutôt de :

1. Sur **production** : restreindre le choix à **une seule** valeur : `v2` si `APPLY_BOOKING_LIMITS_V2` est activé, `v1` sinon. (Ou, mieux : masquer le champ.)

2. Sur **staging**, autoriser les 2 valeurs.

2021-01-25 15:46 UTC, Akhilian commented on src/pcapi/admin/custom_views/beneficiary_user_view.py
> +            ],
J'ai croisé avec Vincent. J'ai retiré la possibilité de choisir la version du deposit de la production pour éviter la confusion ou les erreurs de manipulation. 

J'ai laissé tel quel pour staging et les autres envs (hors prod donc), car la solution `("", "Veuillez sélectionner la version")` me contraindrait à ajouter des validations (prod vs pas prod, et v1 / v2 vs "") qui rendrait le truc complexe.

2021-01-25 15:46 UTC, Akhilian commented on src/pcapi/admin/custom_views/beneficiary_user_view.py
>  from sqlalchemy.orm import query
Yes, j'ai commit un peu mon work in progress vendredi soir

2021-01-26 14:51 UTC, dbaty approved these changes
Je continue à penser que la sélection automatique de la v1 du dépôt dans le formulaire HTML est un risque, mais comme ce n'est que sur staging, je suppose qu'on peut vivre avec.

2021-01-26 15:02 UTC, merged