Suppression de code à l'utilité discutable
pass-culture/pass-culture-api pull request #2000
Opened 2021-02-18 10:24 UTC by dbaty

Commits à relire séparément.

2021-02-18 10:47 UTC, xordoquy approved these changes

2021-02-19 14:12 UTC, Akhilian approved these changes

2021-02-22 09:35 UTC, cgaunet requested changes
create_booking_for_user_on_specific_stock_bypassing_capping_limits est toujours utilisé, on peut voir ensemble comment y remédier ?

2021-02-23 17:00 UTC, merged

2021-02-23 17:02 UTC, dbaty commented
> create_booking_for_user_on_specific_stock_bypassing_capping_limits est toujours utilisé, on peut voir ensemble comment y remédier ?

J'ai gardé. Pour l'instant. ;)