(PC-3962) Add a server deault on bank_information dateModified
pass-culture/pass-culture-api pull request #2024
Opened 2021-02-24 15:57 UTC by viconnex

2021-02-25 09:14 UTC, dbaty approved these changes

2021-02-25 09:33 UTC, apibrac requested changes
Pas sûr de comprendre comment ça résout le pb.
Est ce qu'il ne faut pas au contraire ne pas utiliser une valeur par défaut et extraire la valeur du dossier DMS ?

2021-02-25 17:05 UTC, viconnex commented
> Pas sûr de comprendre comment ça résout le pb.
> Est ce qu'il ne faut pas au contraire ne pas utiliser une valeur par défaut et extraire la valeur du dossier DMS ?

Ok j'ai mis à jour la PR pour que la date soit celle qui vient du dossier

2021-02-25 18:03 UTC, viconnex commented
J'ai aussi trouvé la réponse à ta question @apibrac : 

> A vérifier au passage :
> Il semble qu'en db le champ dateModified soit rempli pour certains records (les bank_information avec statut=draft ?). Il faudrait identifier le bout de code qui fait ça et le modifier ou vérifier qu'il n'entre pas en conflit avec cette tache.
> NB : peut être que ce dateModified est rempli parfois avec la date actuelle, celle à laquelle se fait la synchronisation. Il ne faut pas, le champ dateModified doit correspondre exactement au champ modification_date de DMS (puisque c'est celui-ci qui est utilisé dans la comparaison des checks ci-dessus)

Quand le dossier est créé pour la première fois, on appelle `to_model` avec un objet dont la `date_modified` est None. Mais comme il y avait une valeur par défaut sur le modèle (que j’ai enlevée), la valeur None était écrasée par la datetime.now. 
D'où la nécessité de modifier le test dans le commit n°2.

En revanche, quand tu remodifies l’objet sql et que tu lui set une valeur None (ce qui était fait dans les update ) et bien la valeur par défaut n’est plus prise en compte et None est bien resettée.

2021-02-26 08:55 UTC, apibrac approved these changes

2021-02-26 08:56 UTC, merged