(PC-7160) Reindex offers from fnac synchronization
pass-culture/pass-culture-api pull request #2026
Opened 2021-02-25 10:00 UTC by cgaunet

2021-02-25 10:12 UTC, dbaty commented on src/pcapi/core/offers/repository.py
> +        for (id, id_at_providers, booking_quantity, offerId) in stocks
```suggestion
        id_at_providers: {"id": id, "booking_quantity": booking_quantity, "offer_id": offer_id}
        for (id, id_at_providers, booking_quantity, offer_id) in stocks
```

parce que j'aime bien chipoter ;)

2021-02-25 10:12 UTC, dbaty commented on src/pcapi/local_providers/fnac/synchronize_fnac_stocks.py
> +                redis.add_offer_id(client=app.redis_client, offer_id=stock.offerId)
J'aurais bien mis ces 2 appels dans l'appelant (`synchronize_venue_stocks_from_fnac()`), plus proche après le commit qui suit bulk_save_objects et bulk_update_mappings. Pour 2 raisons :

1. C'est dans `synchronize_venue_stocks_from_fnac` qu'on ajoute et modifie les données, donc à cet endroit qu'on voudrait réindexer.
2. Si on ajoute des identifiants d'offre dans le Redis _avant_ d'avoir commité en base de données, je pense qu'il y a un risque que le cron d'indexation passe alors que les données ne lui sont pas encore visibles. Risque faible, je suppose.

2021-02-26 14:40 UTC, Akhilian requested changes

2021-02-26 14:40 UTC, Akhilian commented on src/pcapi/local_providers/fnac/synchronize_fnac_stocks.py
> +            redis.add_offer_id(client=app.redis_client, offer_id=offer_id)
Je veux bien quelques tests sur ça. Peu de code, mais un peu sensible 😄

2021-02-26 14:40 UTC, Akhilian commented on src/pcapi/local_providers/fnac/synchronize_fnac_stocks.py
> +    return update_stock_mapping, new_stocks, offer_ids
Je veux bien qu'on ajoute quelques tests auto là dessus, le comportement risque d'être perdu / oublié quand on reviendra sur le code.

2021-03-02 08:38 UTC, Akhilian approved these changes

2021-03-02 08:46 UTC, merged