(PC-7141): Compute status in back not front
pass-culture/pass-culture-api pull request #2127
Opened 2021-03-16 09:55 UTC by floragc-octo

2021-03-24 09:44 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
Je ne pense pas qu'il faille introduire la notion de date dans "isSoldOut" -> ça concerne plutôt la propriété `isExpired`

2021-03-24 09:45 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +            .where(or_(Stock.remainingQuantity.is_(None), Stock.remainingQuantity != 0))
ce serait cool d'ajouter une propriété hybride Stock.isSoldOut

2021-03-24 09:58 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
Pour les évènements, cette notion de date est nécessaire cf [la spec](https://www.notion.so/passcultureapp/Offres-b530f629af8d4ffb8e39475bfaa9e9c2#d880fde9db7045868c895fc2e43280a7)
```
épuisée :  l’offre n’a plus de stock restant ou n'a pas encore de stock actif renseigné (non softDeleted)
- Offre physique et numérique :
    - stock dispo = 0
    - pas encore de stock renseigné
    - un seul stock stock.isSoftDeleted = True
- Offre évènement :
    - toutes les dates (stocks) dans le futur ont un stock dispo = 0
    - pas encore de stock renseigné
    - tous les stocks sont supprimées stock.isSoftDeleted = True
```

2021-03-24 10:21 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
Ok je comprends (je me suis fait des noeuds au cerveau). En gros tu considères un stock dans le passé comme inexistant, un peu comme isSoftDeleted.

2021-03-24 10:22 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +        status = OfferStatus.ACTIVE
je mettrais plutôt une valeur par défaut non permissive

2021-03-24 10:42 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +        status = OfferStatus.ACTIVE
Je ne suis pas sûr d'avoir bien compris ton commentaire ; selon nous, le statut `ACTIVE` est justement le défaut, et certaines règles métier définissent ce statut différemment.

2021-03-24 10:51 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
C'est effectivement compliqué :)
L'exemple que j'ai en tête:
Si un concert ce soir est complet, alors qu'hier soir 10 places n'ont pas été vendues, le concert est effectivement épuisé, et non expiré.
Pour la salle de concert, il est ainsi plus facile de filtrer sur les épuisés pour remettre des places en vente.

2021-03-25 09:28 UTC, victorenaud requested changes
Request for changes parce qu'il reste un print dans un test :eyes: 

Sinon je pense qu'il manque des tests sur les nouvelles propriétés + statuts
Vu que c'est un sujet complexe, ça mérite d'avoir une bonne couverture de tests pour avoir une documentation complète et se protéger

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +    # TODO: replace unlimited by None (also in the front-end)
Est-ce que c'est fait ?
Est-ce qu'une action est planifiée pour le faire ?

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +        return case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.bookingsQuantity))
Le retour est différent que la fonction python (qui elle renvoie `"unlimited"` et pas `None`

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +        return self.isSoftDeleted or self.quantity is not None and self.remainingQuantity <= 0
Si un stock est supprimé, il n'est pas épuisé mais juste supprimé non ? :thinking: 
Sinon ce ne serait pas mieux de laisser les parenthèses qui affiche bien les deux conditions ? (soit supprimé, soit plus de quantité)

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +            .where(Stock.offerId == cls.id)
Comment le join est fait ? :monocle_face:

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +            exists().where(Stock.offerId == cls.id).where(Stock.isSoftDeleted.is_(False)),
Pourquoi avoir besoin de le mettre alors que cette condition est également dans l'autre argument ?
C'est un comportement bizarre de `.where(Stock.hasBookingLimitDatetimePassed.is_(False))` qui le demande ?

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/core/offers/repository.py
> +REJECTED_STATUS = "rejected"
Pourquoi le dupliquer alors que c'est également présent dans Offer ?
Notamment parce qu'il manque `INACTIVE` que vous avez rajouté dans Offer

2021-03-25 09:28 UTC, victorenaud commented on src/pcapi/utils/includes.py
> +    "status",
Est-ce que c'est encore utile / utilisé ?

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +    def test_expression_with_stock_with_no_booking_limit_datetime(self):
Ajouter un test sur le comportement lorsqu'il n'y a pas de stock

En effet, il faut que ça renvoie false, sinon le statut de l'offre sera `Expiré` au lieu de `Épuisé`

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
>          expiring_stock = factories.StockFactory(bookingLimitDatetime=datetime.datetime.utcnow())
Plutôt prendre une date dans le passée, là on se fit au fait que le test est fait à la milliseconde

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
>      def test_sold_out(self):
Il y a trois cas de tests pour Épuisé :
- l'offre n'a pas de stocks
- l'offre a un seul stock sans date qui est épuisé
- l'offre a plusieurs stocks, dont certains dans le passé avec du stock restant

Là on ne test que le premier cas

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +    def test_expression_sold_out(self):
Il y a trois cas de tests pour Épuisé :
- l'offre n'a pas de stocks
- l'offre a un seul stock sans date qui est épuisé
- l'offre a plusieurs stocks, dont certains dans le passé avec du stock restant

Là on ne test que le deuxième cas

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
>  class OfferStatusTest:
Aucun des tests ne test le comportement des stocks qui sont `softDeleted`
Est-ce normal ?

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +        # when
Pourquoi donc ?
Si c'est un nouveau standard que l'on veut imposer de les mettre / ne pas les mettre, discutions-en
Mais actuellement en fonction du reviewer on va demander des les mettre ou non
Dans ce cas laissons l'auteur faire ce qu'il souhaite

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +        # when
Il manque quelque chose dans le when, si tu souhaites mettre given/when/then

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +        # then
Il manque le when, si tu souhaites mettre given/when/then

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +class OfferIsSoldOutTest:
Il manque un test avec des stocks dans le passé non épuisés
Et un autre avec un stock softDeleted

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +class StockRemainingQuantityTest:
On ne test que les expressions et pas les propriétés python, est-ce normal ?

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +        assert Offer.query.filter(Stock.remainingQuantity.is_(None)).one() == offer
On a une différence de comportement entre la propriété python et l'expression
Est-ce que ce n'est pas un peu risqué ?

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_models.py
> +        assert stock.remainingQuantity == "unlimited"
On ne test pas l'expression (ni dans les tests d'après)
Normal ?

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_repository.py
> +            # )
:eyes:

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_repository.py
> +            print([offer.name for offer in expired_offers.offers])
:eyes:

2021-03-25 09:28 UTC, victorenaud commented on tests/core/offers/test_repository.py
> +            # assert approved_offers.offers[0].status == OfferStatus.APPROVED.name
:eyes:

2021-03-25 09:39 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +        return case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.bookingsQuantity))
L'expression ne peut pas retourner 2 types différents, alors que la propriété renvoie une `str` ou un `int`.
D'où le TODO pour harmoniser.

2021-03-25 09:46 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +        return case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.bookingsQuantity))
Tu ne pourrais pas faire `case([(cls.quantity.is_("unlimited"), None)], else_=(cls.quantity - cls.bookingsQuantity))` donc ? :thinking: 

Alors priorisons le TODO
Un simple TODO non signé / daté dans le code et non priorisé dans jira, c'est un truc qui va se perdre, et qui nous mordra les doigts plus tard :disappointed:

2021-03-25 09:56 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +        """
_non annulés de ce Stock_

2021-03-25 09:56 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +        return case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.bookingsQuantity))
Absolument, on va signer et faire un ticket

2021-03-25 10:01 UTC, francois-seguin commented on tests/core/offers/test_models.py
>          expiring_stock = factories.StockFactory(bookingLimitDatetime=datetime.datetime.utcnow())
A la _microseconde_ même, donc cent fois moins que le temps de création de l'objet et de son enregistrement en DB.

2021-03-25 10:03 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +    # TODO: replace unlimited by None (also in the front-end)
cf plus bas

2021-03-25 10:06 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +            exists().where(Stock.offerId == cls.id).where(Stock.isSoftDeleted.is_(False)),
Si on a aucun stock qui n'est pas softDeleted on retourne un `False` comme dans la property en dessus. c'est l'équivalent du `if self.activeStocks:`

2021-03-25 10:09 UTC, yacine-pc commented on src/pcapi/utils/includes.py
> +    "status",
Oui on l'envoie calculé maintenant au lieu de le calculer à partir de `isActive` et `validation` dans le front

2021-03-25 10:11 UTC, victorenaud commented on src/pcapi/utils/includes.py
> +    "status",
Pardon, je voulais parler du fichier `includes.py`
Est-ce que les endpoints qui utilisent l'offre ne sont pas déjà tous sur spectree ?

2021-03-25 10:14 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +            exists().where(Stock.offerId == cls.id).where(Stock.isSoftDeleted.is_(False)),
La condition en-dessous ne fait renvoi pas déjà false dans ce cas là ?
Vu qu'elle contient le même début de condition 
```
~exists()
            .where(Stock.offerId == cls.id)
            .where(Stock.isSoftDeleted.is_(False))
            .where(Stock.hasBookingLimitDatetimePassed.is_(False))
```

2021-03-25 10:19 UTC, victorenaud commented on tests/core/offers/test_models.py
>          expiring_stock = factories.StockFactory(bookingLimitDatetime=datetime.datetime.utcnow())
Mais ce ne serait pas plus clair de prendre une date dans le passé ? :monocle_face:

2021-03-25 10:29 UTC, yacine-pc commented on tests/core/offers/test_models.py
> +        offer = factories.OfferFactory(product__type=str(ThingType.INSTRUMENT))
Non pas nécessaire, je l'enlève

2021-03-25 10:45 UTC, francois-seguin commented on tests/core/offers/test_models.py
>          expiring_stock = factories.StockFactory(bookingLimitDatetime=datetime.datetime.utcnow())
S le nom de la variable ne suffit pas, on peut définir une date beaucoup plus loin (genre hier) dans le passé.

2021-03-25 12:56 UTC, yacine-pc commented on src/pcapi/utils/includes.py
> +    "status",
Ah oui, il y'a toujours deux endpoints  `/venues` qui utilisent `OFFER_INCLUDES`

2021-03-25 13:08 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +            exists().where(Stock.offerId == cls.id).where(Stock.isSoftDeleted.is_(False)),
Non dans le cas où une offre n'a pas de stock ou n'a que des stocks supprimés, cette condition seule va retourné un True, car la requête ne va trouver aucune ligne qui match avec `Stock.offerId == cls.id` dans le cas l'offre n'a pas de stock et la requête ne va trouver aucune ligne qui match avec `Stock.isSoftDeleted.is_(False)` dans le cas où l'offre n'a que des stocks supprimés. le `exists()` va donc être `False` et avec la négation devient `True`. Donc on obligé de s'assurer d'abord qu'une offre a des stocks et qui sont pas tous supprimés.

2021-03-25 13:10 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +            .where(Stock.offerId == cls.id)
le join entre `Offer` et `Stock` est fait avec `Stock.offerId == cls.id`, `cls` ici c'est la classe `Offer`. Je ne sais pas si j'ai bien compris ta question

2021-03-25 13:21 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +        return case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.bookingsQuantity))
@victorenaud `quantity` est de type `Integer` dans la base de données donc pas possible de faire `cls.quantity.is_("unlimited")`

2021-03-25 13:26 UTC, yacine-pc commented on tests/core/offers/test_models.py
> +    def test_expression_with_stock_with_no_booking_limit_datetime(self):
Bien vu, test ajouté

2021-03-25 13:29 UTC, yacine-pc commented on tests/core/offers/test_models.py
>  class OfferStatusTest:
Si tu parles des tests de `OfferHasBookingLimitDatetimesPassedTest`, je viens d'ajouter un test pour cela

2021-03-25 13:30 UTC, yacine-pc commented on tests/core/offers/test_models.py
> +    def test_expression_sold_out(self):
Merci, tests ajoutés pour les deux autres cas

2021-03-25 13:31 UTC, yacine-pc commented on tests/core/offers/test_models.py
> +class OfferIsSoldOutTest:
tests ajoutés

2021-03-25 13:39 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +        return case([(cls.quantity.is_(None), None)], else_=(cls.quantity - cls.bookingsQuantity))
Ah, je ne pensais pas qu'on était contraint par cela :(
Merci pour l'apprentissage !

2021-03-25 13:41 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +            .where(Stock.offerId == cls.id)
Pardon, elle n'était pas claire...
Jusqu'à maintenant, quand j'avais besoin d'utiliser un enfant de la classe, je devais faire `.join(Stock)`
Ici tu ne fais jamais de join explicitement, mais tu utilises quand même des attributs de la classe `Stock` enfant
Du coup je me demandais comment ça fonctionnait ?

La dernière fois que j'avais tenté d'accèder à un enfant dans une `expression` ça n'avait pas marché, c'est peut être pour ça !

2021-03-25 13:43 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +            exists().where(Stock.offerId == cls.id).where(Stock.isSoftDeleted.is_(False)),
Ah, je comprends ce que je n'avais pas compris !
Le `~` devant le `exists` est une négation...
C'est plus clair, merci :smile:

2021-03-25 13:46 UTC, victorenaud commented on tests/core/offers/test_models.py
> +        assert Offer.query.filter(Stock.remainingQuantity.is_(None)).one() == offer
L'explication a été donnée sur l'autre thread

2021-03-25 13:51 UTC, victorenaud commented on tests/core/offers/test_models.py
> +    def test_expression_sold_out(self):
Top !
Il faudrait également les ajouter sur la propriété python

2021-03-25 13:56 UTC, victorenaud commented on src/pcapi/utils/includes.py
> +    "status",
Arf, normalement ça ne devrait pas durer alors ! :crossed_fingers:

2021-03-25 14:39 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +            .where(Stock.offerId == cls.id)
on utilise ici les expressions SQLA `exists()` puis `where()`, la syntaxe est différente d'un `db.query()`

2021-03-25 14:40 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +            .where(or_(Stock.remainingQuantity.is_(None), Stock.remainingQuantity != 0))
C'est vrai, mais je ne préfère pas surcharger cette PR :)

2021-03-25 14:42 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +            if self.hasBookingLimitDatetimesPassed:  # pylint: disable=using-constant-test
Note: Ces directives Plyint sont nécessaires car Pylint ne traite pas correctement les hybrid_properties de SQLA, cf https://github.com/PyCQA/pylint/issues/1061

2021-03-25 15:03 UTC, francois-seguin commented on tests/core/offers/test_models.py
>      def test_sold_out(self):
On teste `isSoldOut` plus bas, on teste ici le `status`

2021-03-25 15:08 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +        # pylint: disable=comparison-with-callable
A défaut d'utiliser Stock.isSoldOut dans le modèle Offer.isSoldOut pour le moment, est-ce tu peux modifier cette propriété `isSoldOut` pour qu'elle soit en phase avec la définition que tu as mise (notamment la notion : si événement dans le passé alors soldOut même s'il reste une place) ?

2021-03-25 15:19 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +            if self.hasBookingLimitDatetimesPassed:  # pylint: disable=using-constant-test
est-ce qu'il ne faut pas prendre en compte la date des événements des stocks aussi ?

2021-03-25 15:24 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +            if self.hasBookingLimitDatetimesPassed:  # pylint: disable=using-constant-test
La spec explicite que l'on doit considérer la date limite de réservation, quelque soit le `Type`.

2021-03-25 15:27 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +        status = OfferStatus.ACTIVE
ok

2021-03-25 15:33 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +            if self.hasBookingLimitDatetimesPassed:  # pylint: disable=using-constant-test
ok
oui de toute façon la date de l'événement sera toujours après cette date

2021-03-25 15:57 UTC, francois-seguin commented on src/pcapi/core/offers/models.py
> +            if self.hasBookingLimitDatetimesPassed:  # pylint: disable=using-constant-test
Absolument, il y au un _trigger_ en ce sens.

2021-03-25 16:24 UTC, francois-seguin approved these changes

2021-03-25 16:31 UTC, francois-seguin commented on tests/core/offers/test_models.py
> +        # when
Soit, sans consensus, on reste sur les goûts et les couleurs -> je supprime le commentaire

2021-03-25 17:04 UTC, viconnex approved these changes

2021-03-25 17:06 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +        """ query qui renvoie la quantité de Bookings non annulés de ce Stock """
est-ce que ce commentaire est vraiment utile ? 
au moins l'écrire en anglais

2021-03-25 17:29 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
Du coup, juste pour être sûr, ça implique : **un événement expiré est forcément épuisé**.

(`stock.beginningDateTime < now => isSoldOut = True`)

J'en ai parlé à Lina qui n'a pas l'air convaincue.

2021-03-26 08:35 UTC, victorenaud approved these changes

2021-03-26 08:44 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +        """ query qui renvoie la quantité de Bookings non annulés de ce Stock """
Oui c'est pas vraiment utile, la requête est déjà assez claire, je vais le supprimer

2021-03-26 08:48 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
Un événement expiré est un qui a des dates limites de réservation dans le passé. cf. [fiche notion](https://www.notion.so/passcultureapp/Offres-b530f629af8d4ffb8e39475bfaa9e9c2#11bb1cad3d484381bd393f86a4d8af87)
Je vais confirmer ça avec Lina ou Charlotte.

2021-03-26 09:52 UTC, viconnex commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
(Oui du coup, comme elles sont dans le passé, cette fonction retournera `isSoldOut = True`)

2021-03-26 10:12 UTC, victorenaud commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
Le calcul du statut restera correct, vu qu'on vérifie avant si l'offre est expirée
Donc l'offre sera expirée, même si sa propriété `isSoldOut` est également à true

Qu'une offre expirée soit sold-out ça ne me choque pas
Tant que le calcul de statut est là pour gérer la hiérarchie des status

2021-03-26 13:06 UTC, yacine-pc commented on src/pcapi/core/offers/models.py
> +                and (stock.beginningDatetime is None or stock.beginningDatetime > datetime.utcnow())
La condition de date c'est pour ne pas prendre en compte les `remainingQuantity` des stocks dans le passé comme l'a expliqué François avec un exemple au-dessus.

2021-03-26 15:57 UTC, merged