(PC-7738): Fraude - annulation reservations
pass-culture/pass-culture-api pull request #2174
Opened 2021-03-23 16:40 UTC by floragc-octo

2021-03-24 10:31 UTC, dbaty requested changes

2021-03-24 10:31 UTC, dbaty commented on src/pcapi/core/bookings/api.py
> +    booking.isCancelled = True
Il faut absolument vérifier ici que la réservation n'est ni déjà annulée, ni déjà utilisée.

2021-03-24 10:31 UTC, dbaty commented on src/pcapi/core/bookings/api.py
> +    logger.info("Cancelling booking for fraud reason: %s", booking.id)
```suggestion
    logger.info("Cancelled booking for fraud reason", extra={"booking": booking.id})
```

(J'ai une PR en cours qui reprend les logs de ce module, et c'est le format utilisé.)

2021-03-24 10:31 UTC, dbaty commented on src/pcapi/core/bookings/repository.py
> +def find_deletable_bookings_by_beneficiaries(users: List[User]) -> List[Booking]:
```suggestion
def find_cancellable_bookings_by_beneficiaries(users: List[User]) -> List[Booking]:
```

2021-03-24 10:48 UTC, floragc-octo commented on src/pcapi/core/bookings/api.py
> +    booking.isCancelled = True
Exact, erreur de ma part. Je fourni une liste qui a déjà effectué cette verif mais bien évidemment il le faut ici aussi. Bien vu, merci

2021-03-26 08:48 UTC, dbaty approved these changes
J'ai juste mis 1 commentaire à propos du mail envoyé à l'offreur, mais c'est peut-être que je manque de contexte, ça n'est pas forcément bloquant. :)

À part ce détail, ça me paraît très bien ! :)

2021-03-26 08:48 UTC, dbaty commented on src/pcapi/core/bookings/validation.py
> +def check_booking_can_be_cancelled(booking: Booking) -> None:
Bonne idée, car ça n'est finalement pas spécifique à une annulation par un offreur.

2021-03-26 08:48 UTC, dbaty commented on src/pcapi/domain/user_emails.py
> +        send_offerer_driven_cancellation_email_to_offerer(booking)
Est-ce que ça ne risque pas d'étonner l'offreur :

- de recevoir un mail intitulé "Confirmation de votre annulation de réservation" alors que ce n'est pas l'offreur qui a annulé ? (Peut-être qu'on prévoir d'améliorer le mail plus tard, mais je pense qu'il faudra le garder en tête.)
- de potentiellement recevoir un gros volume de ces mails lors d'un nettoyage de masse (comme il est prévu ici) ?

2021-03-26 11:12 UTC, floragc-octo commented on src/pcapi/domain/user_emails.py
> +        send_offerer_driven_cancellation_email_to_offerer(booking)
Bonne remarque, on a déjà eu la conversation avec Charlotte, je lui repose la question au cas où et on avise

2021-03-26 14:34 UTC, floragc-octo commented on src/pcapi/domain/user_emails.py
> +        send_offerer_driven_cancellation_email_to_offerer(booking)
j'ai remplacé par user-driven-cancellation-email-to-offerer. Ce n'est pas la réalité mais ça convient à notre cas (vu avec Charlotte)

2021-03-26 14:34 UTC, merged