(PC-7905): Add view for venue provider
pass-culture/pass-culture-api pull request #2217
Opened 2021-04-01 13:38 UTC by Akhilian

2021-04-02 07:30 UTC, cgaunet commented on src/pcapi/admin/base_configuration.py
> -    else:
C'est cool de pouvoir logger les accès utilisateurs :)

2021-04-12 10:30 UTC, apibrac requested changes

2021-04-12 10:30 UTC, apibrac commented on src/pcapi/routes/serialization/venue_provider_serialize.py
> +    authToken: Optional[str]
Pas le token !
Et pas besoin d'exposer l'apiUrl non plus je pense

2021-04-12 10:30 UTC, apibrac commented on src/pcapi/use_cases/connect_venue_to_provider.py
> +def connect_venue_to_provider(venue: Venue, provider: Provider, venueIdAtOfferProvider: str = None) -> VenueProvider:
Est ce qu'il ne faudrait pas déplacer aussi cette fonction vu que l'archi cible est sans use_case ?

Où est ce qu'elle est censée attérir ?
La différence avec la fonction api.create_venue_provider est pas très clair c'est peut être la même action non ?

2021-04-12 10:32 UTC, apibrac commented on src/pcapi/routes/pro/venue_providers.py
> -# @debt api-migration
🎉 🎉 👏

2021-04-12 14:03 UTC, Akhilian commented on src/pcapi/routes/serialization/venue_provider_serialize.py
> +    authToken: Optional[str]
D'acc :)
J'avoue, j'ai fait en sorte d'être ISO sur l'output mais du coup on pourra rationnaliser le truc :)

2021-04-12 14:13 UTC, apibrac commented on src/pcapi/routes/serialization/venue_provider_serialize.py
> +    authToken: Optional[str]
Je crois qu'on faisait un delete manuel pour pas les exposer
Mais clairement avec ce ProviderResponse c'est beaucoup plus 👌

2021-04-15 09:39 UTC, dbaty approved these changes
Gros boulot, chapeau ! :)

J'ai principalement des commentaires sur la forme (et notamment des rappels pour fusionner certains commits avant le merge final), rien de vraiment bloquant.

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/admin/custom_views/venue_provider_view.py
> +            label="ID du lieu",
Je pense que c'est un peu dangereux de demander à l'utilisateur de saisir un identifiant de lieu (*), plutôt que de sélectionner un lieu dans une liste. Mais vu le nombre de lieux, on ne pourrait pas utiliser un simple `select`, il faudrait un champ de sélection avec auto-complétion.

(*) surtout qu'il n'y a pas d'unicité sur `VenueProvider.venueId`. Même si actuellement on pourrait peut-être avoir plusieurs providers, je ne pense pas que ce soit utilisé en pratique, et à mon avis c'est plus un piège qu'autre chose.

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/admin/custom_views/venue_provider_view.py
> +            venueIdAtOfferProvider=form.venueIdAtOfferProvider.data,
Commit "Allow to define venueIdAtOfferProvider while creating..." à fusionner avec le commit "Allow venue_provider creation...".

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/admin/custom_views/venue_provider_view.py
> -    def is_visible(self) -> bool:
Commit "Make all venue provider visible from menu" à fusionner avec un autre (celui qui ajoute `VenueProviderView`, je suppose)

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/admin/custom_views/venue_provider_view.py
> +        form_class.venueId = None
Commit "Prevent edition that would break" à fusionner avec un commit précédent (probablement celui qui ajoute la vue d'édition).

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/routes/pro/venue_providers.py
> +    venue_provider_payload.venueIdAtOfferProvider = None
Je ne comprends pas cette ligne. Soit on accepte le paramètre dans le body (et on supprime cette ligne), soit le body ne devrait pas avoir ce champ et le portail pro ne devrait pas le fournir.

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/routes/serialization/venue_provider_serialize.py
> -    apiUrl: Optional[str]
commit "apiUrl and authToken should not be exposed" à fusionner avec le commit "Implement spectree on venue provider creation".

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/core/providers/api.py
> +    id_at_provider = venueIdAtOfferProvider if venueIdAtOfferProvider else venue.siret
(détail)

```suggestion
    id_at_provider = venueIdAtOfferProvider or venue.siret
```

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/core/providers/models.py
> +
2ème(*) commit "Moving a use case into the core api folder" à renommer en quelque chose comme "Move AllocineVenueProviderPriceRule to 'providers' sub-package"

(*) 2 commits ont le même message, je parle du second commit.

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/sandboxes/scripts/creators/helpers/sql_creators.py
>  from pcapi.models import UserOfferer
2 fichiers (temporaires, je suppose) ont été ajoutés par mégarde dans le commit "Move Provider to models file" : 

- src/pcapi/sandboxes/thumbs/mediations/EventType.MUSEES_PATRIMOINE
- src/pcapi/sandboxes/thumbs/mediations/EventType.PRATIQUE_ARTISTIQUE

2021-04-15 09:39 UTC, dbaty commented on tests/admin/custom_views/venue_provider_view_test.py
> +        assert view.is_accessible() is False
(détail)

```suggestion
        assert view.is_accessible()
```

2021-04-15 09:39 UTC, dbaty commented on tests/admin/custom_views/venue_provider_view_test.py
> +        assert view.is_accessible() is False
(détail)

```suggestion
        assert not view.is_accessible()
```

2021-04-15 09:39 UTC, dbaty commented on tests/admin/custom_views/venue_provider_view_test.py
> +    @patch("pcapi.admin.custom_views.venue_provider_view.api.create_venue_provider")
Je trouve dommage de _mocker_ la fonction principale, dans ce test. Est-ce que quelque chose empêche de de l'utiliser ? À mon avis, on ne devrait pas mocker, et vérifier qu'un VenueProvider a bien été créé avec les caractéristiques souhaitées.

2021-04-15 09:39 UTC, dbaty commented on tests/admin/custom_views/venue_provider_view_test.py
> +        assert f"{venue.id}" in link
détail

```suggestion
        assert str(venue.id) in link
```

2021-04-15 09:39 UTC, dbaty commented on tests/admin/custom_views/venue_view_test.py
> +        assert f"{venue.id}" in link
(détail)

```suggestion
        assert str(venue.id) in link
```

2021-04-15 09:39 UTC, dbaty commented on src/pcapi/core/providers/api.py
> +from pcapi.use_cases.connect_venue_to_allocine import connect_venue_to_allocine
Cette fonction `connect_venue_to_allocine` pourrait aussi être rapatriée dans le module `core.providers.api`.

2021-04-15 09:39 UTC, dbaty commented on tests/core/providers/post_venue_provider_test.py
> +    def test_prevent_creation_for_non_existing_provider(self):
Il me semble que c'est le seul test qui fait appel à `create_venue_provider`. Je pense qu'on devrait écrire au moins un test minimal (qui créé un VenueProvider sans erreur) pour cette fonction.

2021-04-15 09:39 UTC, dbaty commented on tests/routes/pro/post_venue_provider_test.py
>      class Returns201:
On devrait supprimer la class parente `Post` qui n'apporte rien (le nom du fichier commence déjà `post_`) et nous oblige à configurer pytest d'une façon telle que des avertissements sont levés à tort (cf. [mon commentaire ici](https://github.com/pass-culture/pass-culture-api/blob/56f849aab8e9764ad81a2205f3177615c4a6b987/pytest.ini#L6-L15)).

(Dommage de ne pas avoir modifié les tests pour utiliser des factories à la place des fonctions de ` from pcapi.model_creators.generic_creators` et `pcapi.model_creators.provider_creators`. Oui, je sais que c'est assez fastidieux et pas très excitant... :) Bon, au pire on pourra le faire "plus tard".)

2021-04-16 10:07 UTC, Akhilian commented on src/pcapi/admin/custom_views/venue_provider_view.py
> +        "provider.isActive": "Source de données disponible",
Deal. J'ai tenté une traduction en pensant au support et aux bizdevs en supposant que Provider n'aiderait pas nécessairement à comprendre. On verra si on a besoin d'expliquer.

2021-04-16 10:09 UTC, Akhilian commented on src/pcapi/routes/pro/venue_providers.py
> +    venue_provider_payload = body
Certe ^^
Ça simplifiait la magie de l'IDE de conserver le nommage et donc la définition.

2021-04-16 10:12 UTC, Akhilian commented on src/pcapi/admin/custom_views/venue_provider_view.py
> +            label="ID du lieu",
Je ne crois pas qu'il y ait d'auto complique sur Flask admin, et comme une liste risque d'être très longue, ce n'est pas idéal non plus. J'en discute avec Vincent lundi.

2021-04-16 11:43 UTC, Akhilian commented on src/pcapi/routes/pro/venue_providers.py
> +    venue_provider_payload.venueIdAtOfferProvider = None
J'ai utilisé `PostVenueProviderBody` comme interface pour valider la création d'une synchro/d'un venueProvider mais fonctionnellement, l'API n'autorise pas l'utilisation du paramètre `venueIdAtOfferProvider`. Du coup, j'ai bloqué manuellement l'utilisation de ce paramètre pour éviter d'introduire un comportement qu'on ne souhaite pas ici.

Ceci dit, c'est pas très clair. Je regarde si je peux faire un truc pour ça

2021-04-16 11:45 UTC, Akhilian commented on tests/core/providers/post_venue_provider_test.py
> +    def test_prevent_creation_for_non_existing_provider(self):
Yes, je voulais faire ça mais vu le volume de code déjà modifié, je me suis reposé sur les tests qui existent déjà plutôt que de toucher aux tests en même temps et risquer d'induire une régression. En gardant les tests actuels (j'ai ajouté 1 test qui manquait en gros), c'était plus safe.

2021-04-16 12:13 UTC, Akhilian commented on tests/routes/pro/post_venue_provider_test.py
>      class Returns201:
J'avoue, j'y ai pensé ... et ma flemme a été plus forte ahah

2021-04-16 13:09 UTC, apibrac commented on src/pcapi/admin/custom_views/venue_view.py
> +        return None
ça fait pas du N+1 query ça ?
Et peut être qu'on pourrait ne faire qu'un exist pour avoir cette info plutôt que de remonter tous les venue_provider ?

C'est par curiosité, vu que c'est un admin + uniquement 10 venues par page + max1 venue_provider par venue pour l'instant perds pas de tps là dessus

2021-04-16 13:10 UTC, apibrac approved these changes

2021-04-19 15:24 UTC, merged