(PC-8118) Add sendinblue to send phone validation code
pass-culture/pass-culture-api pull request #2307
Opened 2021-04-20 14:51 UTC by viconnex

2021-04-21 15:58 UTC, jeremieb-pass commented on src/pcapi/notifications/sms/backends/sendinblue.py
> +    def send_transactional_sms(self, content, recipient):
typage manquant : paramètres et valeur de retour.

2021-04-21 15:58 UTC, jeremieb-pass commented on src/pcapi/core/users/constants.py
> +METROPOLE_PHONE_PREFIX = "33"
Peut-être utiliser un `defaultdict` ?

2021-04-21 15:58 UTC, jeremieb-pass commented on src/pcapi/core/users/utils.py
> +    return phone_prefix + user.phoneNumber[1::]
`user.phoneNumber[1:]` suffit non ?

2021-04-22 08:44 UTC, viconnex commented on src/pcapi/core/users/constants.py
> +METROPOLE_PHONE_PREFIX = "33"
je trouve pas ça hyper lisible :/

2021-04-22 09:53 UTC, jeremieb-pass requested changes

2021-04-22 09:53 UTC, jeremieb-pass commented on src/pcapi/notifications/sms/__init__.py
> +def send_transactional_sms(recipient: str, content: str) -> None:
la fonction renvoie un `bool` non ?
Si oui, il y a trois autres types de retour à corriger pour des `send_transactional_sms`.

2021-04-23 09:38 UTC, jeremieb-pass approved these changes

2021-05-03 16:02 UTC, merged