(PC-8399) add isPhoneValidated to User
pass-culture/pass-culture-api pull request #2345
Opened 2021-04-28 12:48 UTC by jeremieb-pass

2021-04-28 13:07 UTC, xordoquy approved these changes

2021-04-28 13:07 UTC, xordoquy commented on src/pcapi/alembic/versions/20210428_22b38fe83d5a_add_isphonevalidated_to_user.py
> +    # ### commands auto generated by Alembic - please adjust! ###
```suggestion
    # ### commands auto generated by Alembic ###
```

2021-04-28 13:07 UTC, xordoquy commented on src/pcapi/alembic/versions/20210428_22b38fe83d5a_add_isphonevalidated_to_user.py
> +    # ### commands auto generated by Alembic - please adjust! ###
```suggestion
    # ### commands auto generated by Alembic ###
```

2021-04-29 08:39 UTC, viconnex commented on src/pcapi/alembic/versions/20210428_22b38fe83d5a_add_isphonevalidated_to_user.py
> +    op.add_column("user", sa.Column("isPhoneValidated", sa.Boolean(), server_default=sa.text("false"), nullable=False))
`nullable=False` ? ça va pas poser problème ?

2021-04-29 08:39 UTC, viconnex requested changes
`nullable=False` ? ça va pas poser problème ?

2021-04-29 09:36 UTC, xordoquy commented
> `nullable=False` ? ça va pas poser problème ?

avec la valeur par défaut "fixe" ça ne devrait pas.

2021-04-29 10:08 UTC, jeremieb-pass commented
Le ticket a légèrement évolué. Pour un meilleur suivi, cette PR est fermée. Une nouvelle va être créée.

2021-04-29 10:08 UTC, closed without merging