(PC-8243): Migrate id at providers to new format (Part 1)
pass-culture/pass-culture-api pull request #2361
Opened 2021-04-30 15:10 UTC by Akhilian

2021-05-05 08:40 UTC, cgaunet commented on src/pcapi/local_providers/allocine/allocine_stocks.py
> +                Offer, venue_movie_original_version_unique_id, datetime.utcnow(), venue_movie_original_version_unique_id
J'ai l'impression que tu répètes deux fois le même argument là non ?

2021-05-05 08:40 UTC, cgaunet commented on src/pcapi/local_providers/allocine/allocine_stocks.py
> +                Offer, venue_movie_french_version_unique_id, datetime.utcnow(), venue_movie_french_version_unique_id
idem J'ai l'impression que tu répètes deux fois le même argument là non ?

2021-05-05 08:43 UTC, cgaunet commented on src/pcapi/local_providers/titelive_things/titelive_things.py
> +            Product, book_unique_identifier, book_information_last_update, book_information_last_update
On veut changer le id_at_provider sur les produits ? :thinking:

2021-05-05 08:44 UTC, cgaunet commented on src/pcapi/local_providers/titelive_things/titelive_things.py
> +            Product, book_unique_identifier, book_information_last_update, book_information_last_update
Tu mets la date d'update ici non dans le id_at_provider ? ^^

2021-05-05 08:49 UTC, cgaunet commented on src/pcapi/scripts/migrate_id_at_providers.py
> +    db.session.commit()
Je comprends pas bien ta pagination là, j'ai l'impression qu'on save les 1000 premiers puis tout le reste ensuite ?

2021-05-05 09:08 UTC, cgaunet commented on src/pcapi/scripts/migrate_id_at_providers.py
> +    db.session.commit()
Ok, cf le commit d'après ^^

2021-05-05 16:07 UTC, apibrac reviewed
Il y a aussi des idAtProviders dans stock (les même, mais peut être pas à remplacer de la même manière), est-ce que ça serait pris en compte dans une part 2 ?

2021-05-05 16:07 UTC, apibrac commented on src/pcapi/core/providers/api.py
> +            id_at_provider=stock_detail["products_provider_reference"],
Qu'est ce que tu pense d'utiliser le offers_provider_reference et en créer un autre pour le id_at_provideres legacy ?
Sinon en nettoyant on risque de ne plus utiliser qu'un products_provider_reference

Après ça peut être la cible vu que ça sera le même, à débattre...

2021-05-05 16:07 UTC, apibrac commented on src/pcapi/local_providers/generic_provider/generic_stocks.py
> +            self.provider_stocks["ref"],
Code mort, que tu peux supprimer plutôt que d'updater si tu veux

2021-05-05 16:07 UTC, apibrac commented on src/pcapi/scripts/migrate_id_at_providers.py
> +                    "idAtProviders": offer[1],
Pourquoi update le idAtProviders ?

2021-05-05 16:07 UTC, apibrac commented on tests/core/bookings/test_repository.py
> +        assert bookings[1] == past_event_booking
Qu'est ce qui s'est passé ? Est ce qu'il y aurait un ordre non déterministe ?

2021-05-05 16:07 UTC, apibrac commented on src/pcapi/local_providers/local_provider.py
> +        providable_info.new_id_at_provider = new_id_at_provider
J'ai pas très bien compris à quoi il servait ce providable_info ?
C'est le squelette d'une offre ?

2021-05-06 13:00 UTC, Akhilian commented on src/pcapi/alembic/versions/20210430_e8199ef92975_migrate_id_at_provider_part_2.py
> +    op.execute('CREATE UNIQUE INDEX CONCURRENTLY "venueId_idAtProvider_index" ON offer ("venueId", "idAtProvider")')
Alembic encapsule les migrations dans une transaction. Sauf que la création d'un index CONCURRENTLY n'est pas possible. Donc, on met fin à la transaction avec un commit.

2021-05-06 13:10 UTC, Akhilian commented on tests/core/bookings/test_repository.py
> +        assert bookings[1] == past_event_booking
Notre BDD qui se construit via Docker a un comportement sur l'ordre des données en BDD.

2021-05-06 13:13 UTC, Akhilian commented on src/pcapi/local_providers/local_provider.py
> +        providable_info.new_id_at_provider = new_id_at_provider
C'est une sorte de ValueObject, qui contient les infos minimals de synchro.
J'ai surtout assuré le fonctionnement ISO mais y a un nettoyage a faire.

2021-05-06 13:45 UTC, dbaty requested changes

2021-05-06 13:45 UTC, dbaty commented on src/pcapi/alembic/versions/20210430_20290f0b5d4f_migrate_id_at_provider_part_1.py
> +    op.add_column("offer", sa.Column("idAtProvider", sa.String(length=70), nullable=True))
Pourquoi 70 caractères ? Je propose d'utiliser une colonne `TEXT` pour tout champ textuel dont on ne contrôle pas vraiment la longueur. Ça : 
- évite de se poser des questions sur "est-ce que c'est la bonne limite ? pourquoi cette limite et pas une autre ?"
- évite des migrations douloureuses quand on s'aperçoit qu'en fait la limite n'est pas correcte ;
- n'a probablement aucun impact notable sur les performances à notre petit niveau.

2021-05-06 13:45 UTC, dbaty commented on src/pcapi/alembic/versions/20210430_e8199ef92975_migrate_id_at_provider_part_2.py
> +    op.execute('CREATE UNIQUE INDEX CONCURRENTLY "venueId_idAtProvider_index" ON offer ("venueId", "idAtProvider")')
Je crois que la question d'Alexis portait sur l'ordre des colonnes dans l'index. Et je pense que c'est un bon ordre, car cet index servira aussi quand on fera des requêtes filtrant sur le lieu (`venueId`) seulement. Cf. ma proposition d'ajout de FIXME plus bas.

2021-05-06 13:45 UTC, dbaty commented on src/pcapi/core/offers/models.py
> +    Index("venueId_idAtProvider_index", venueId, idAtProvider, unique=True)
Pourrais-tu ajouter un FIXME dans ce genre :

```python
# FIXME: We shoud be able to remove the index on `venueId`, since this composite index
# can be used by PostgreSQL when filtering on the `venueId` column only.
```

2021-05-06 13:45 UTC, dbaty commented on src/pcapi/scripts/migrate_id_at_providers.py
> +def migrate_id_at_providers() -> None:
Je pense qu'il y a une façon plus optimisée de faire cette migration. Plutôt que de faire des SELECT + UPDATE nous-mêmes, on pourrait laisser PotsgreSQL faire l'UPDATE tout seul.

Code pas vraiment testé (je ne suis pas spécialiste du traitement de texte en SQL), mais c'est l'idée :

```
UPDATE offer
SET 
    "idAtProvider" = substring("idAtProviders" from '([^@]+)@')
WHERE "idAtProviders" IS NOT NULL
```

Ça devrait être bien plus efficace. Éventuellement on peut faire des lots pour ne pas traiter toute la table en une seule requête, mais je ne suis même pas sûr que ce soit nécessaire.

2021-05-06 13:49 UTC, dbaty commented on tests/core/bookings/test_repository.py
>          assert future_event_booking not in bookings
Si l'ordre n'est pas prévisible, on devrait comparer des *sets* :past_event_booking}` ?

```suggestion
        assert set(bookings) == {thing_booking, past_event_booking}
```

2021-05-06 15:10 UTC, Akhilian commented on src/pcapi/alembic/versions/20210430_e8199ef92975_migrate_id_at_provider_part_2.py
> +    op.execute('CREATE UNIQUE INDEX CONCURRENTLY "venueId_idAtProvider_index" ON offer ("venueId", "idAtProvider")')
Ah, yes. J'avais mal compris la question.
J'ai ajouté le FIXME comme tu le suggérais.

2021-05-06 16:15 UTC, apibrac commented on src/pcapi/core/offers/models.py
> +    Index("venueId_idAtProvider_index", venueId, idAtProvider, unique=True)
Autant enlever l'index sur venue tout de suite non ? On est pas sur que l'index multiple puisse remplacer ?

2021-05-06 16:28 UTC, dbaty commented on src/pcapi/core/offers/models.py
> +    Index("venueId_idAtProvider_index", venueId, idAtProvider, unique=True)
Je suis à peu près sûr qu'on peut enlever l'index, oui. (Mais même si c'était moi, je ferais des tests avant, pour être sûr que je ne me trompe pas. ;) )

2021-05-06 16:29 UTC, apibrac commented on src/pcapi/alembic/versions/20210430_e8199ef92975_migrate_id_at_provider_part_2.py
> +    op.execute('CREATE UNIQUE INDEX CONCURRENTLY "venueId_idAtProvider_index" ON offer ("venueId", "idAtProvider")')
Oui tout à fait c'était pas très clair sorry
En effet c'est pas mal d'utiliser le même index pour les 2 queries

Il y aurait l'autre approche de faire 2 index très différents pour les 2 requêtes
ça donnerait un index `UNIQUE ("idAtProvider", "venueId") WHERE "idAtProvider" IS NOT NULL`
plus coûteux pour les insertions mais plus efficace niveau perf ? Vu que l'index est plus petit et qu'il y a plus de variabilité côté idAtProvider

Après je suis pas sûr que le gain serait visible
L'autre intérêt de deux index différents serait que le premier (sur venueId) pourrait être ordonné d'après la requête qui l'utilise, apparemment c'est par "offer.id", ce qui est pas possible dans l'index multiple, ça reste très prospectif...

2021-05-25 16:13 UTC, dbaty reviewed
Ça m'a l'air bien, mais j'ai vraiment du mal avec le script de remplissage de `idAtProvider`. Je pense que le code que j'ai proposé est plus lisible et plus efficace.

2021-05-25 16:13 UTC, dbaty commented on src/pcapi/scripts/migrate_id_at_providers.py
> +def migrate_id_at_providers() -> None:
En lisant [la doc](https://www.postgresql.org/docs/12/functions-string.html), j'ai trouvé une fonction SQL qui fait exactement ce qu'on veut (et plus lisiblement que mon exemple avec `substring()`) : `split_part`. Ça donnerait :

```sql
UPDATE offer
SET 
    "idAtProvider" = split_part("idAtProviders", '@', 1)
WHERE "idAtProviders" IS NOT NULL
```

**Je recommande vraiment d'utiliser ça** : ce sera bien plus efficace que la version avec des SELECT+INSERT en masse.

À froid, ça pourrait ressembler à ça (non testé !) :

```python
from pcapi.models import db
from sqlalchemy import func

# Taille du batch à déterminer, mais franchement ça devrait rouler tranquille.
# Pour rappel, on a supprimé les triggers sur la table "offer".
BATCH_SIZE=100_000

def populate_offer_id_at_provider():
    max_id = db.session.query(func.max(Offer.id)).scalar()
    ranges = [(i, i + BATCH_SIZE) for i in range(1, max_id + 1, BATCH_SIZE)]
    for start, end in ranges:
        db.session.execute(
            """
            UPDATE offer
            SET "idAtProvider" = split_part("idAtProviders", '@', 1)
            WHERE
              id BETWEEN :start AND :end
              AND "idAtProvider" IS NOLL
              AND "idAtProviders" IS NOT NULL
            """,
            {"start": start, "end": end},
        )
        db.session.commit()
```

Le code me semble plus court, plus lisible et plus performant.

2021-05-25 16:13 UTC, dbaty commented on src/pcapi/scripts/migrate_id_at_providers.py
> +        Offer.query.filter(Offer.idAtProviders.isnot(None))
il faut aussi ne prendre que les offres où `idAtProvider` est NULL (pas encore rempli).

2021-05-25 16:13 UTC, dbaty commented on tests/core/providers/test_api.py
> +                "products_provider_reference": "isbn_product_ref",
pourquoi changer cette valeur ? (idem plus bas)

2021-05-25 16:13 UTC, dbaty commented on tests/core/providers/test_api.py
> +        assert new_offer.idAtProvider == "isbn_product_ref"
On pourrait tester cette valeur dans le `assert new_offers == [...]` plus haut. D'ailleurs, tous ces nouveaux assert sur `new_offer` font doublon avec l'`assert new_offers == [...]`, non ?

2021-05-26 16:15 UTC, merged