(PC-7795) Add expiration dates for activation codes
pass-culture/pass-culture-api pull request #2419
Opened 2021-05-11 15:25 UTC by cgaunet

2021-05-12 13:12 UTC, Akhilian requested changes

2021-05-12 13:12 UTC, Akhilian commented on src/pcapi/core/offers/validation.py
> +    if booking_limit_datetime is None and activation_codes_expiration_datetime is not None:
Je déplacerais bien les tests de cette partie du code au niveau des tests du `test_api.py`.
Je trouve ça toujours dangereux de n'avoir des tests qu'au niveau de la route, sachant que c'est surtout le comportement de `upsert_stocks` dans qu'on veut assurer pour le futur. WYT ?

Ce sera plus simple d'identifier un défaut si c'est le `core` qui remonte un problème que si c'est une route.

2021-05-12 13:12 UTC, Akhilian commented on src/pcapi/routes/serialization/stock_serialize.py
> +        if len(activationCodes) > 0 and isinstance(activationCodes[0], ActivationCode):
Je ne suis pas sûr de comprendre le rôle de `isinstance(activationCodes[0], ActivationCode):`
Cette propriété `activationCodes` est nécessairement un `ActivationCode` ou je loupe un truc ?

2021-05-12 13:12 UTC, Akhilian commented on tests/routes/pro/get_stocks_test.py
> +                    "activationCodes": ["DEF", "ABC"],
A-t-on besoin d'exposer les codes ?
Ça me parait dangereux de rendre les codes visibles, je les garderais bien secret une fois uploadé.

2021-05-12 14:22 UTC, cgaunet commented on src/pcapi/routes/serialization/stock_serialize.py
> +        if len(activationCodes) > 0 and isinstance(activationCodes[0], ActivationCode):
On modifie la nature des activationCodes pour qu'ils soient de la forme list[str] ensuite ici

2021-05-12 14:23 UTC, cgaunet commented on tests/routes/pro/get_stocks_test.py
> +                    "activationCodes": ["DEF", "ABC"],
Il faut que je check côté pro à quel point c'est complexe d'avoir un modèle de stock d'édition différent de celui de création en sachant que les deux sont sur le même composant.
Si c'est OK je fais cette modif de ne renvoyer que deux infos: hasActivationCodes et l'expirationDatetime :)

2021-05-12 14:23 UTC, cgaunet commented on src/pcapi/routes/serialization/stock_serialize.py
> +        if len(activationCodes) > 0 and isinstance(activationCodes[0], ActivationCode):
Avec mon commentaire ci-dessous ça va peut-être partir anyway

2021-05-12 14:28 UTC, cgaunet commented on src/pcapi/core/offers/validation.py
> +    if booking_limit_datetime is None and activation_codes_expiration_datetime is not None:
Les deux ? :)

2021-05-17 08:18 UTC, dbaty approved these changes

2021-05-17 08:18 UTC, dbaty commented on src/pcapi/core/offers/validation.py
> +                " d'au moins 7 jours à la date limite de réservation"
Le message d'erreur ne me paraît pas tout à fait clair. Contre-proposition :

> Une date limite de validité a été renseignée. Dans ce cas, il faut également renseigner une date limite de réservation qui doit être antérieure d'au moins 7 jours.

2021-05-17 09:46 UTC, Akhilian approved these changes

2021-05-17 12:33 UTC, merged