PC-7342/ajout-prod-cors-autorises
pass-culture/pass-culture-api pull request #2809
Opened 2021-07-07 09:49 UTC by bba-pass

Ajouter web.passculture.app passculture.app et passculture.pro aux CORS autorisés

2021-07-08 07:33 UTC, mmachado-pass commented on .env.production
> +CORS_ALLOWED_ORIGIN=^https://(app|pro)\.passculture\.beta\.gouv\.fr|https://passculture.\(app|pro)|https://web\.passculture.\app$
D'après regex101, la requête n'est pas bonne. Tout ne match pas.

2021-07-12 15:44 UTC, apibrac approved these changes

2021-07-12 15:44 UTC, apibrac commented on .env.production
> +CORS_ALLOWED_ORIGIN=^https://(app|pro)\.passculture\.beta\.gouv\.fr|https://passculture\.(app|pro)|https://web\.passculture\.app$
A quoi sert web.passculture.app ?

2021-07-12 16:23 UTC, apibrac requested changes
Sur suggestion de @francois-seguin : besoin de rajouter des tests pour ne pas bloquer l'app au déploiement

2021-07-16 11:40 UTC, closed without merging