(PC-10260) Prepare switch to webapp v2 with feature flipping
pass-culture/pass-culture-api pull request #2944
Opened 2021-08-03 15:41 UTC by BenStirrup

2021-08-03 16:52 UTC, xordoquy reviewed
il ne manquerait pas une migration pour ajouter le feature flag ?

2021-08-03 17:28 UTC, BenStirrup commented
> il ne manquerait pas une migration pour ajouter le feature flag ?

J'ai run `pc alembic revision --autogenerate -m add_feature_toggle_webapp_v2_enabled` mais la migration est vide : 
```python
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
```

2021-08-03 20:12 UTC, xordoquy commented
oui, c'est normal. Les feature flag sont de la donnée et non de la structure. Un exemple de migration: https://github.com/pass-culture/pass-culture-api/blob/master/src/pcapi/alembic/versions/20210630_29c8b67b67a5_add_beneficiary_validation_after_fraud_.py

2021-08-04 07:35 UTC, BenStirrup commented
> oui, c'est normal. Les feature flag sont de la donnée et non de la structure. Un exemple de migration: https://github.com/pass-culture/pass-culture-api/blob/master/src/pcapi/alembic/versions/20210630_29c8b67b67a5_add_beneficiary_validation_after_fraud_.py

Nicket c'est fait, merci !

2021-08-04 11:07 UTC, kopax-polyconseil commented on src/pcapi/alembic/versions/20210803_bebba9216847_add_feature_toggle_webapp_v2_enabled.py
> +    feature.add_feature_to_database(FLAG)
C'est normal que down et upgrade sont pareil ?

2021-08-04 11:07 UTC, kopax-polyconseil commented on src/pcapi/models/feature.py
Webapp v2

2021-08-04 11:22 UTC, BenStirrup commented on .env.testing
>  OBJECT_STORAGE_URL=https://storage.googleapis.com/passculture-metier-ehp-testing-assets
for m'a l'air plus approprié, puisqu'on c'est une web app dont l'objectif est de faire une redirection

2021-08-04 11:22 UTC, BenStirrup commented on src/pcapi/alembic/versions/20210803_bebba9216847_add_feature_toggle_webapp_v2_enabled.py
> +    feature.add_feature_to_database(FLAG)
bien vu, ca doit être remove

2021-08-04 14:23 UTC, mmachado-pass commented on .env.integration
> +WEBAPP_FOR_NATIVE_REDIRECTION=passculture://app.passculture.integration
Il n'y a pas une typo ?

2021-08-04 14:31 UTC, BenStirrup commented on .env.integration
> +WEBAPP_FOR_NATIVE_REDIRECTION=passculture://app.passculture.integration
Hum en fait on a pas d'integration (pour le moment) pour l'app de redirection, la webapp v2 et l'app native
Donc dans ces les variables d'env ne signifient pas grand chose

2021-08-05 07:21 UTC, mmachado-pass commented on helm/pcapi/values.production.yaml
> +  WEBAPP_FOR_NATIVE_REDIRECTION: https://passculture.app
Tu as déclaré 2 fois ce type de variable. le déclarer à un sel endroit suffit. .env ou configmap :)

2021-08-05 07:31 UTC, xordoquy requested changes
normalement, il devrait y avoir une modification du fichier `alembic_version_conflict_detection.txt` qui permet de détecter les conflits sur les migrations avant de merger. Il faudra réinstaller les hooks de commit suite à [cette modification](https://github.com/pass-culture/pass-culture-api/commit/1a7caeb3dd4eed34d8b824c7d254fd3d19000856) et ajouter manuellement la modification avec le commit de la migration (voir [ce commit par exemple](https://github.com/pass-culture/pass-culture-api/commit/1a7caeb3dd4eed34d8b824c7d254fd3d19000856))

2021-08-05 07:33 UTC, BenStirrup commented on helm/pcapi/values.production.yaml
> +  WEBAPP_FOR_NATIVE_REDIRECTION: https://passculture.app
ok ca marche, je le retire de configmap

2021-08-05 07:48 UTC, xordoquy approved these changes

2021-08-05 11:44 UTC, merged