(PC-10269) add new pro route: PUT /venues/id/contact
pass-culture/pass-culture-api pull request #2947
Opened 2021-08-04 15:16 UTC by jeremieb-pass

**Besoin**

Côté PRO, on veut que l'utilisateur ait la possibilité de renseigner des informations de contact d'un lieu : email, numéro de téléphone et réseaux sociaux.

Seule l'adresse email est obligatoire.

**Implémentation**

1. Création d'une table venue_contact qui contient ces informations.
2. Ajout d'une route `PUT /venues/<id>/contact` qui va créer un écraser les informations de contact d'un lieu.

**Note**

La partie validation du numéro de téléphone qui était dans users.api / users.utils a été déplacée dans un module à part puisque le modèle Pydantic de mise à jour des informations de contact en a besoin.

2021-08-04 15:46 UTC, jeremieb-pass commented on src/pcapi/core/validation/phone_number.py
> +            parsed_phone_number = phonenumbers.parse(phone_number)
le paramètre region a été ajouté afin de permettre l'ajout d'un numéro au format local, par exemple : 0102030405 (et non +33102030405), mais ce sera le téléphone au format international qui sera sauvegardé en base.

2021-08-04 15:47 UTC, jeremieb-pass commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
Si quelqu'un sait comment éviter ça, et le faire côté SQLAlchemy je suis preneur 😢

2021-08-05 06:35 UTC, apibrac reviewed
T'as un fichier vide :
src/pcapi/core/validation/exceptions.py

2021-08-05 06:35 UTC, apibrac commented on src/pcapi/core/offerers/models.py
> +    contact = relationship("VenueContact", back_populates="venue", uselist=False)
que va devenir le bookingEmail ?

2021-08-05 06:35 UTC, apibrac commented on src/pcapi/core/offerers/models.py
> +class VenueContact(PcObject, Model):
Pourquoi avoir créé une nouvelle table plutôt que de tout mettre dans venue ?

2021-08-05 06:35 UTC, apibrac commented on src/pcapi/routes/serialization/venues_serialize.py
> +    def from_orm(cls, contact: offerers_models.VenueContact) -> "GetVenueContactResponseModel":
Pourquoi le type de retour est une string ?

2021-08-05 06:35 UTC, apibrac commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
J'ai pas compris l'utilité de cette ligne 🤔 
C'est pour avoir la valeur par default `{}` ?

2021-08-05 07:46 UTC, jeremieb-pass commented on src/pcapi/core/offerers/models.py
> +    contact = relationship("VenueContact", back_populates="venue", uselist=False)
le bookingEmail c'est l'adresse de réception des notifications d'un lieu non ? Ce qui n'est pas forcément ce qu'on veut du coup.

2021-08-05 07:47 UTC, jeremieb-pass commented on src/pcapi/core/offerers/models.py
> +class VenueContact(PcObject, Model):
Pour éviter d'avoir une table énorme, vu qu'on n'aura besoin de ces informations que de temps en temps.

2021-08-05 07:49 UTC, jeremieb-pass commented on src/pcapi/routes/serialization/venues_serialize.py
> +    def from_orm(cls, contact: offerers_models.VenueContact) -> "GetVenueContactResponseModel":
Si je ne dis pas de bêtise c'est pour indiquer qu'on retourne une instance de soi-même (ici GetVenueContactResponseModel qui n'est pas encore défini à ce moment)

2021-08-05 07:50 UTC, jeremieb-pass commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
Oui. Les valeurs par défaut de SQLA permettent d'indiquer ce qu'on va insérer en base, mais ça ne permet pas d'avoir une valeur par défaut sur le champ 😢

2021-08-06 13:11 UTC, jeremieb-pass commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
Non, j'ai l'impression qu'il faut que : 

1. l'objet soit (vraiment) sauvegardé en base ;
2. que SQL le charge en mémoire

et là, tu as ton `dict`.

Si tu crées l'objet, sans plus, tu as `None`. J'ai l'impression que dans une transaction, le champ sera toujours `None` 😢 Donc je ne préfère pas m'aventurer et partir du principe qu'on aura la valeur par défaut (d'ailleurs dans les tests, on récupère un `None` même si on refait un `VenueContact.query.get(venue_contact.id)`.

2021-08-06 13:23 UTC, xordoquy commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
l'upsert fait avant la sérialization devrait y mettre une valeur non ?

2021-08-06 14:41 UTC, jeremieb-pass commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
Dans les tests, j'ai ce comportement :

```python
def upsert_venue_contact(venue: Venue, contact_data: venues_serialize.EditVenueContactBodyModel) -> models.VenueContact:
    """
    Create and attach a VenueContact to a Venue if it has none.
    Update (replace) an existing VenueContact otherwise.
    """
    venue_contact = venue.contact
    if not venue_contact:
        venue_contact = models.VenueContact(venue=venue)

    venue_contact.email = contact_data.email
    venue_contact.phone_number = contact_data.phone_number
    venue_contact.social_medias = contact_data.social_medias

    repository.save(venue_contact)

    # import ipdb; ipdb.set_trace()
    # ipdb> contact_data
    # EditVenueContactBodyModel(email='other.contact@venue.com', phone_number=None, social_medias=None)
    # ipdb> venue_contact.social_medias is None
    # True
    # ipdb> models.VenueContact.query.get(venue_contact.id).social_medias is None
    # True

    return venue_contact
```

Après les tests se font dans un contexte particulier, mais entre SQLA et Flask-SQLA je ne sais pas dans quelle mesure on risque de se retrouver dans ces cas similaires en staging/production.

2021-08-06 18:20 UTC, xordoquy commented on src/pcapi/core/offerers/api.py
> +    venue_contact.social_medias = contact_data.social_medias
```suggestion
    venue_contact.social_medias = contact_data.social_medias or {}
```
Ce permettra d'éviter d'avoir des None dans social_medias

2021-08-06 18:20 UTC, xordoquy commented on src/pcapi/routes/serialization/venues_serialize.py
> +        return super().from_orm(contact)
En effet, mais du coup, c'est lors de la création qu'il faut corriger ça (j'ai ajouté un commentaire la dessus).

2021-08-06 18:21 UTC, xordoquy commented on src/pcapi/core/offerers/api.py
> +    venue_contact.social_medias = contact_data.social_medias
ou alors:
```suggestion
    if contact_data.social_medias:
        venue_contact.social_medias = contact_data.social_medias
```

2021-08-16 07:57 UTC, xordoquy requested changes

2021-08-16 07:57 UTC, xordoquy commented on src/pcapi/core/offerers/models.py
> +    social_medias = Column(JSONB, nullable=False, default={}, server_default="{}")
ll reste un petit gotcha ici. Les modifications dans les champs JSON/JSONB ne sont pas détectées automatiquement.
Dans le back, - en général - on change d'autres champs et c'est pris en compte, mais si ton utilisateur ne change que le `social_medias`, je pense que SQLAlchemy ne détectera pas la modification et n'enregistrera pas le résultat.
Pour contourner, il faut passer ça dans un [MutableType.as_mutable](https://docs.sqlalchemy.org/en/14/orm/extensions/mutable.html#sqlalchemy.ext.mutable.Mutable.as_mutable) comme fait [ici](https://github.com/pass-culture/pass-culture-api/blob/2ff50bbf395e4d9a232ee18440944bec25028ea1/src/pcapi/core/users/models.py#L149)

2021-08-16 08:01 UTC, xordoquy commented on src/pcapi/core/validation/phone_number.py
> +            parsed_phone_number = phonenumbers.parse(phone_number)
Est-ce que l'on a des tests "unitaires" sur cette fonction et sur le fonctionnement avec le code région ?

2021-08-16 08:02 UTC, xordoquy reviewed
Je ne suis pas fan de l'emplacement de `src/pcapi/core/validation/phone_number.py`. Est-ce que l'on ne pourrait pas le mettre dans `src/pcapi/utils/` ?

2021-08-18 09:03 UTC, xordoquy approved these changes

2021-08-18 09:03 UTC, xordoquy commented on src/pcapi/routes/serialization/venues_serialize.py
> +    contact: VenueContactModel
Il est obligatoire ?

2021-08-18 10:28 UTC, jeremieb-pass commented on src/pcapi/routes/serialization/venues_serialize.py
> +    contact: VenueContactModel
Non. J'avais hésité à l'ajouter. Je l'enlève du coup.

2021-08-19 15:35 UTC, merged