pc-9914: Script is too slow and one part of it does not even work, adding some corrections
pass-culture/pass-culture-api pull request #2984
Opened 2021-08-12 15:33 UTC by ymedaghriPass

2021-08-13 12:43 UTC, victorenaud commented on src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Je pense que tu peux supprimer purement et simplement
idem pour le commentaire au-dessus, non ?

Ou alors mettre un #FIXME en précisant les conditions qui permetteraient de corriger cela

2021-08-13 12:43 UTC, victorenaud commented on src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
idem ici

2021-08-13 12:43 UTC, victorenaud commented on tests/conftest.py
> +    # app.config["SQLALCHEMY_ECHO"] = True
Je pense que tu peux supprimer cette ligne :eyes:

2021-08-13 12:43 UTC, victorenaud commented on tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
> +def test_delete_cascade_offerer_should_remove_offers_of_offerer():
Le test de la ligne 53 n'était pas suffisant / clair ?

2021-08-13 13:47 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Je vais mettre un fix me

2021-08-13 13:53 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
pareil, je vais mettre un fixme

2021-08-13 13:54 UTC, ymedaghriPass commented on tests/conftest.py
> +    # app.config["SQLALCHEMY_ECHO"] = True
Moi je l'aime bien quand je veux remettre l'affichage des requêtes sql j'ai pas besoin de me casser la tête pour la retrouver :(

2021-08-13 14:00 UTC, ymedaghriPass commented on tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
> +def test_delete_cascade_offerer_should_remove_offers_of_offerer():
En fait je n'aime pas le test de la ligne 53, il contient differentes choses qui dene me plaisent pas : 
D'abord ils ne vérifient pas qu'on peut supprimer une offre sans stock, ou une venue sans offre par exemple, ils suppriment stock + venue + offre
Mais surtout c'est le assert qui me déplait : 
assert Offerer.query.count() == 1
assert Venue.query.count() == 1
assert Offer.query.count() == 1
assert Stock.query.count() == 1

Pourquoi n'a t'on pas assert... = 0, parceque offers_factories.StockFactory() créé implicitement un offerer + une venue + une offer + un stock (ca je n'aime pas trop dans ce cadre là)

2021-08-13 14:02 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Done

2021-08-13 14:02 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Done

2021-08-13 14:05 UTC, victorenaud commented on tests/conftest.py
> +    # app.config["SQLALCHEMY_ECHO"] = True
Alors plutôt faire comme dans `flask_app.py` : ne pas commenter, mais mettre à `False`
D'ailleurs est-ce que le paramètre dans `flask_app.py` ne fonctionne pas dans ce contexte ?

2021-08-13 14:05 UTC, victorenaud commented on tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
> +def test_delete_cascade_offerer_should_remove_offers_of_offerer():
Ok, ça me va !

J'avais fait un test qui laissait à 1 pour vérifier également que je ne supprimais pas trop de choses

2021-08-13 14:06 UTC, victorenaud approved these changes

2021-08-13 19:09 UTC, dbaty requested changes

2021-08-13 19:09 UTC, dbaty commented on src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Puisque l'objectif est de _désindexer_ ces offres, on peut directement appeler `search.unindex_offer_ids(offer_ids_to_delete)` ici (au lieu de `reindex_offer_ids()`). Cette fonction ne fait pas de requête à la base de données pour récupérer les offres, donc elle n'aura pas besoin que les offres "existent" encore. (C'est une nouvelle fonction qui est apparue lors de la réorganisation du code en un sous-package `pcapi.core.search`.)

2021-08-14 07:27 UTC, dbaty reviewed
Le message de commit ne me paraît pas très clair : qu'est-ce qui ne fonctionne pas, qu'est-ce qui est lent ?

2021-08-14 07:27 UTC, dbaty commented on src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Idem ici, on peut aussi appeler `search.unindex_offer_ids(offer_ids_to_delete)`. (Attention, cette fonction est synchrone, mais vu qu'on est dans un script, ça ne devrait pas poser de problème.)

2021-08-16 07:34 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Effectivement je pense aussi que la motivation originale d'ajouter cet appel était bien la désindexation des offres.
Je vais apporter la modification indiquée

2021-08-16 07:35 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
En effet.

2021-08-16 07:39 UTC, ymedaghriPass commented on tests/conftest.py
> +    # app.config["SQLALCHEMY_ECHO"] = True
2. Non le paramètre app.config["SQLALCHEMY_ECHO"] de flask_app.py ne marche pas dans le contexte des tests.
1. Je vais le mettre à False dans ce cas

2021-08-16 07:47 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Done

2021-08-16 07:47 UTC, ymedaghriPass commented on src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
> +    # search.reindex_offer_ids(offer_ids_to_delete)
Done

2021-08-16 07:47 UTC, ymedaghriPass commented on tests/conftest.py
> +    # app.config["SQLALCHEMY_ECHO"] = True
Done

2021-08-17 09:02 UTC, dbaty approved these changes

2021-08-17 09:30 UTC, merged