Pc 10387 send email 5 days before expiration books
pass-culture/pass-culture-api pull request #3220
Opened 2021-09-16 12:59 UTC by thig-pc

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10387

## But de la pull request

Ajout d'un nouveau template mailjet d'avertissement d'expiration de réservation envoyé aux bénéficiaires avec 2 paramètres additionnel _days_before_cancel_ et _days_from_booking_ pour alimenter les variables du template de mail dédié au cas du nouveau délai de retrait des livres et autres réservations.

##  Implémentation
- Ajout de l'id du nouveau template dans la fonction build_soon_to_be_expired_bookings_recap_email_data_for_beneficiary
- Ajout de classes de test pour les nouvelles fonctions à utiliser si FF _ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS_ est activé.
- Ajout de classes de test pour les nouvelles fonctions
- Ajout de 2 nouveaux paramètres  _days_before_cancel_ et _days_from_booking_

Ajouts de 4 fonctions : 
- build_soon_to_be_expired_books_bookings_recap_email_data_for_beneficiary
- _extract_books_bookings_information_from_bookings_list
- build_soon_to_be_expired_other_bookings_recap_email_data_for_beneficiary
- _extract_other_bookings_information_from_bookings_list

##  Informations supplémentaires
N/A

​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2021-09-17 15:15 UTC, yacine-pc commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +        if offer.subcategoryId == subcategories.LIVRE_PAPIER.id:
```suggestion
        if offer.subcategoryId == subcategories.LIVRE_PAPIER.id and booking.dateCreated > BOOKS_BOOKINGS_AUTO_EXPIRY_DELAY_START_DATE:
```
Seules les réservations sur des livres créées après la date du début d'application du nouveau délai sont concernés par l'email de relance au bout de 5 jours

2021-09-20 07:12 UTC, thig-pc commented on .gitignore
> +.vscode/settings.json
pas vu ce fichier. VSCode l'a rajouté par défaut, c'est une configuration individuelle qui contient notamment le chemin vers le virtualenv entre autres. Mon avis est que ce n'est pas un fichier à partager.

2021-09-20 07:21 UTC, thig-pc commented on src/pcapi/domain/user_emails.py
> +                beneficiary, books_bookings, 5, 5
ok

2021-09-20 07:22 UTC, thig-pc commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +    beneficiary: User, bookings: list[Booking], days_before_cancel: int = 10, days_from_booking: int = 20
ok

2021-09-20 07:27 UTC, thig-pc commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +def filter_books_bookings(bookings: list[Booking]) -> Tuple[List[Booking], List[Booking]]:
j'ai pensé que cela n'avait pas de rapport avec les emails 
mais avec des données de type booking

2021-09-20 07:36 UTC, thig-pc commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +        if offer.subcategoryId == subcategories.LIVRE_PAPIER.id:
est-ce que ce n'est pas redondant avec la fonction du repository qui va chercher les données de booking ?

2021-09-20 07:36 UTC, thig-pc commented on src/pcapi/domain/user_emails.py
> +                beneficiary, other_bookings, 10, 20
ok

2021-09-20 07:41 UTC, thig-pc commented on src/pcapi/domain/user_emails.py
> +                beneficiary, books_bookings, 5, 5
okr

2021-09-20 07:43 UTC, thig-pc commented on src/pcapi/domain/user_emails.py
> +    if not FeatureToggle.ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS.is_active():
Pas d'avis là dessus je fais le changement. Est-ce que dois prévoir le cas ou la FF n'existe pas ?

2021-09-20 08:08 UTC, francois-seguin commented on .gitignore
> +.vscode/settings.json
Je laisse @cgaunet et @viconnex voir avec toi ce qu'il faut faire du fichier dans le repo.

2021-09-20 08:09 UTC, francois-seguin commented on src/pcapi/domain/user_emails.py
> +    if not FeatureToggle.ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS.is_active():
Le ticket de suppression d'un FF comportera également le nettoyage du code.

2021-09-20 13:03 UTC, thig-pc commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +        if offer.subcategoryId == subcategories.LIVRE_PAPIER.id:
ok ce n'est pas redondant, j'ai inclus cet ajout

2021-09-20 14:45 UTC, francois-seguin commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +        if offer.subcategoryId == subcategories.LIVRE_PAPIER.id:
Peut-on tester cette fonction `filter_books_bookings()` ?

2021-09-20 14:48 UTC, francois-seguin commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +            offer.subcategoryId == subcategories.LIVRE_PAPIER.id
```suggestion
        if (
            booking.stock.offer.subcategoryId == subcategories.LIVRE_PAPIER.id
```

2021-09-20 14:50 UTC, francois-seguin reviewed
Quelques modifications de tests et ce sera bon.

2021-09-20 14:50 UTC, francois-seguin commented on tests/domain/user_emails_test.py
> +        assert mails_testing.outbox[0].sent_data["Vars"]["days_from_booking"] == 23
Peut-on faire une assertion sur le nombre d'emails envoyés?

2021-09-20 14:50 UTC, francois-seguin commented on tests/domain/user_emails_test.py
> +        assert mails_testing.outbox[1].sent_data["MJ-TemplateID"] == 12345
Peut-on faire ici aussi une assertion sur le nombre d'emails envoyés?

2021-09-21 11:16 UTC, francois-seguin commented on tests/emails/beneficiary_soon_to_be_expired_bookings_test.py
> +        assert other_bookings == []
Pour simplifier et tester avec exactitude, on peut:
- créer des variables de `Bookings`
- vérifier que books_bookings == [<bookings préalablement affectés à des variables>]

2021-09-21 11:16 UTC, francois-seguin commented on tests/emails/beneficiary_soon_to_be_expired_bookings_test.py
> +        assert len(books_bookings) == 1
idem que plus haut:
Pour simplifier et tester avec exactitude, on peut:

- créer des variables de Bookings
- vérifier que books_bookings == [<réservations de livres>]
- vérifier que other_bookings == [<autre réservations>]

2021-09-21 11:16 UTC, francois-seguin commented on tests/emails/beneficiary_soon_to_be_expired_bookings_test.py
> +    def test_filter_books_bookings_with_one_book_and_one_other_booking(self, app):
On peut fusionner avec la fonction précédente, et tester en une fois que les réservations de livres vont dans la première liste et les autres dans la seconde liste

2021-09-21 16:04 UTC, francois-seguin approved these changes

2021-09-21 16:04 UTC, francois-seguin commented on tests/emails/beneficiary_soon_to_be_expired_bookings_test.py
> +        assert len(other_bookings) == 1
```suggestion
```
On teste juste en-dessous l'égalité

2021-09-21 16:04 UTC, francois-seguin commented on tests/emails/beneficiary_soon_to_be_expired_bookings_test.py
> +        assert len(other_bookings) == 1
```suggestion
```
idem plus haut

2021-09-22 07:43 UTC, yacine-pc requested changes

2021-09-22 07:43 UTC, yacine-pc commented on src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
> +        "Mj-TemplateID": 3095065,
Pareil que l'autre PR, l'envoi du nouveau template est conditionné par `ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS.is_active()`

2021-09-22 07:43 UTC, thig-pc commented on .gitignore
> +.vscode/settings.json
j'ai retiré ce changement du gitignore

2021-09-22 08:22 UTC, yacine-pc approved these changes

2021-09-22 08:23 UTC, merged