Pc 10386/confirmation email beneficiary new book expiration delay
pass-culture/pass-culture-api pull request #3226
Opened 2021-09-16 15:39 UTC by thig-pc

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10386

## But de la pull request

Ajout d'un nouveau template mailjet de confirmation de réservation envoyé aux **bénéficiares** avec un paramètre additionnel expiration_delay pour gérer le cas du nouveau délai de retrait des livres.

##  Implémentation

Ajout de l'id du nouveau template et l'utiliser dans le cas ou le FF ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS est activé.
Ajout du nouveau paramètre expiration_delay.
Ajout d'une classe de test pour le comportement FF désactivé qui sera supprimé une fois le FF activé.
Ajout d'une classe de test pour le comportement FF activé.

​
##  Informations supplémentaires
N/A
​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2021-09-17 10:58 UTC, francois-seguin commented on src/pcapi/emails/beneficiary_booking_confirmation.py
> +        "MJ-TemplateID": 3094927,
Veut-on basculer définitivement vers ce nouveau template, ou cela est-ce conditionné par `ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS.is_active()` ?

2021-09-17 10:58 UTC, francois-seguin commented on tests/core/bookings/test_api.py
> +        assert email_data2["MJ-TemplateID"] == 3094927  # to beneficiary
idem que plus haut

2021-09-17 10:58 UTC, francois-seguin commented on tests/emails/beneficiary_booking_confirmation_test.py
> +        "MJ-TemplateID": 3094927,
idem que plus haut

2021-09-17 10:58 UTC, francois-seguin commented on tests/emails/beneficiary_booking_confirmation_test.py
> +@override_features(ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS=True)
Pourrait-on créer une classe de tests avec le FF activé, et l'une avec le FF désactivé ?
Cela permettra de plus facilement faire le nettoyage une fois le FF supprimé de la codebase.
Exemple: https://github.com/pass-culture/pass-culture-api/pull/3201/files

2021-09-17 14:08 UTC, thig-pc commented on src/pcapi/emails/beneficiary_booking_confirmation.py
> +        "MJ-TemplateID": 3094927,
ce que j'ai compris du ticket c'est qu'on bascule définitvement vers le nouveau template, 
puis lorsque le FF est actif, on met en place les nouveaux délais

2021-09-17 14:14 UTC, thig-pc commented on src/pcapi/emails/beneficiary_booking_confirmation.py
> +        "MJ-TemplateID": 3094927,
une auto-critique de mon code. Devrais-je baser expiration_delay sur les constantes suivantes 
BOOKINGS_AUTO_EXPIRY_DELAY = datetime.timedelta(days=30)
BOOKS_BOOKINGS_AUTO_EXPIRY_DELAY = datetime.timedelta(days=10)

voir src/pcapi/core/bookings/conf.py

2021-09-20 14:43 UTC, thig-pc commented on tests/emails/beneficiary_booking_confirmation_test.py
> +@override_features(ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS=True)
ok

2021-09-20 14:59 UTC, francois-seguin approved these changes

2021-09-20 14:59 UTC, francois-seguin commented on tests/emails/beneficiary_booking_confirmation_test.py
> +    def test_should_return_specific_expiration_delay_data_for_email_when_offer_is_a_book_and_FF_is_disabled(self):
```suggestion
    def test_should_return_legacy_expiration_delay_data_for_email_when_offer_is_a_book(self):
```

2021-09-20 14:59 UTC, francois-seguin commented on tests/emails/beneficiary_booking_confirmation_test.py
> +    def test_should_return_specific_expiration_delay_data_for_email_when_offer_is_a_book_and_FF_is_active(self):
```suggestion
    def test_should_return_new_expiration_delay_data_for_email_when_offer_is_a_book(self):
```

2021-09-22 07:40 UTC, yacine-pc requested changes

2021-09-22 07:40 UTC, yacine-pc commented on src/pcapi/emails/beneficiary_booking_confirmation.py
> +        "MJ-TemplateID": 3094927,
Le nouveau template est conditionné par `ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS.is_active()`, on veut pas basculer définitvement vers ce nouveau template

2021-09-22 08:20 UTC, yacine-pc approved these changes

2021-09-22 08:27 UTC, merged