(PC-10942) pro: improve get _offerer route performance
pass-culture/pass-culture-api pull request #3275
Opened 2021-09-22 17:21 UTC by francois-seguin

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10942

## But de la pull request

(Ajout de fonctionnalités, Problèmes résolus, etc)

##  Implémentation

- (Ajouts de modèles, Changements significatifs)
​
##  Informations supplémentaires

- Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
- Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2021-09-28 15:36 UTC, cgaunet commented on src/pcapi/utils/rest.py
> +    return obj_class.query.get_or_404(dehumanize(human_id))
First et get produisent le même résultat de prendre le premier s'il y en a plusieurs ?

2021-09-28 15:38 UTC, cgaunet commented on src/pcapi/routes/pro/stocks.py
> +        abort(400)
404 ?

2021-09-28 15:38 UTC, cgaunet commented on src/pcapi/routes/pro/stocks.py
> +        abort(400)
404 ?

2021-09-28 15:40 UTC, cgaunet commented on tests/routes/pro/get_offerer_test.py
> +            10  # check_user_has_access_to_offerer
Ça vient d'où ces 10 requêtes ??

2021-09-28 15:41 UTC, francois-seguin commented on src/pcapi/utils/rest.py
> +    return obj_class.query.get_or_404(dehumanize(human_id))
Cela me semble piégeux que cette fonction prenne le premier élément, car son nom laisse penser qu'il y a un seul objet en DB pour cet id.

2021-09-28 15:42 UTC, francois-seguin commented on src/pcapi/routes/pro/stocks.py
> +        abort(400)
J'ai hésité, car on abandonne quand on donne un mauvais ID d'offre.
Mais 404 me parait cohérent.

2021-09-28 15:42 UTC, francois-seguin commented on src/pcapi/routes/pro/stocks.py
> +        abort(400)
idem plus haut

2021-09-28 15:44 UTC, francois-seguin commented on tests/routes/pro/get_offerer_test.py
> +            10  # check_user_has_access_to_offerer
Peut-être un effet de pytest+flask+SQLA ? Je dois creuser.
Le test unitaire de check_user_has_access_to_offerer() me dénombre 3 requêtes.

2021-09-28 15:45 UTC, cgaunet commented on src/pcapi/utils/rest.py
> +    return obj_class.query.get_or_404(dehumanize(human_id))
J'ai checké toutes les utilisations, ok pour passer en get, c'est des ids qui sont utilisés :)

2021-09-28 15:46 UTC, dbaty commented on tests/routes/pro/get_offerer_test.py
> +            10  # check_user_has_access_to_offerer
@francois-seguin : piste : créer l'URL avant le `assert_num_queries()`. SQLAlchemy a tendance à parfois re-faire un SELECT pour récupérer un attribut car il pense que l'objet correspondant qu'il a en session n'est plus à jour.

2021-09-28 15:46 UTC, cgaunet commented on tests/routes/pro/get_offerer_test.py
> +            10  # check_user_has_access_to_offerer
Yes, parce que c'est chelou, je veux bien regarder aussi

2021-09-28 18:20 UTC, francois-seguin commented on tests/routes/pro/get_offerer_test.py
> +            10  # check_user_has_access_to_offerer
Corrigé !
C'était le client de test qui ajoutait des queries.

2021-09-29 06:39 UTC, dzen commented on src/pcapi/core/offerers/repository.py
> +from datetime import date
a mon avis, tu peux importer datetime ;)

(ceci est mon opinion, les commentaires sur la forme sont hors de propos, je sais :( )

2021-09-29 06:39 UTC, dzen commented on src/pcapi/core/offerers/repository.py
> +        offerers_models.UserOfferer.query.filter_by(offererId=offerer_id).join(User).with_entities(User.email).one()[0]
with_entities retourne un tuple c'est ça ? d'ou le [0] final ?

2021-09-29 06:39 UTC, dzen commented on src/pcapi/core/users/models.py
> +    def has_access(self, offerer_id: int) -> bool:
👍

2021-09-29 06:39 UTC, dzen commented on src/pcapi/core/users/models.py
> +            .scalar()
il ne manque pas le exists() ici ? le scalaire retourne le nombre de row ? est-ce que le exists n'est pas plus rapide ?

2021-09-29 06:39 UTC, dzen commented on src/pcapi/routes/serialization/offerers_serialize.py
> -    visualDisabilityCompliant: Optional[bool]
on a un changement d'API ici non ? est-ce qu'on est sur que les consommateurs de cette API ne vont pas casser ?

2021-09-29 06:57 UTC, xordoquy reviewed
Joli travail ! Merci pour le découpage des commits

2021-09-29 06:57 UTC, xordoquy commented on src/pcapi/core/users/models.py
> +            .scalar()
> Return the first element of the first result or None if no rows present. If multiple rows are returned, raises MultipleResultsFound.

https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.scalar

Si on veut chipoter un peu, on pourrait demander à ne retourner que l'ID pour ne pas avoir tout l'objet à traiter.

2021-09-29 06:57 UTC, xordoquy commented on src/pcapi/routes/pro/stocks.py
> +        abort(400)
Il faudra que l'on soit homogènes. Il me semblait que l'on utilisait plutôt un `raise ApiErrors()` pour renvoyer une erreur 400 dans le reste du code.

2021-09-29 06:57 UTC, xordoquy commented on src/pcapi/core/offerers/repository.py
> +def has_venue_missing_bank_information(offerer_id: int) -> bool:
La formulation me pique un peu. On ne pourrait pas faire quelque chose de plus clair comme (par exemple):
```suggestion
def does_venue_have_empty_bank_information(offerer_id: int) -> bool:
```

2021-09-29 06:57 UTC, xordoquy commented on src/pcapi/core/offerers/repository.py
> +def is_digital_venue_having_offers(offerer_id: int) -> bool:
idem, quelque chose comme:
```suggestion
def do_all_digital_venues_have_offers(offerer_id: int) -> bool:
```

2021-09-29 07:16 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +from datetime import date
J'ai déplacé sans refacto cette partie, je vais effectivement économiser une ligne d'import.

2021-09-29 07:22 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +        offerers_models.UserOfferer.query.filter_by(offererId=offerer_id).join(User).with_entities(User.email).one()[0]
Absolument !

2021-09-29 07:25 UTC, francois-seguin commented on src/pcapi/routes/serialization/offerers_serialize.py
> -    visualDisabilityCompliant: Optional[bool]
En cours de vérification par un collègue front, mais on a eu tendance à sérialiser trop d'information.

2021-09-29 07:46 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +def has_venue_missing_bank_information(offerer_id: int) -> bool:
Il me semble qu'il y a une habitude de nommage des fonctions retournant un bool, à savoir préfixer par `is` ou `has`.
`has_venue_without_bank_information()` peut-être ?

2021-09-29 07:50 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +def is_digital_venue_having_offers(offerer_id: int) -> bool:
Je n'étais pas fier de ce nom...
Toujours avec l'idée de préfixer avec is ou has, je propose: `has_digitial_venue_with_at_least_one_offer()` car un offreur ne peut avoir qu'un lieu numérique.

2021-09-29 07:55 UTC, lixxday commented on src/pcapi/core/offerers/repository.py
> +def has_venue_missing_bank_information(offerer_id: int) -> bool:
Dans ce cas, `is_venue_missing_bank_information` me parait plus anglais 
"I am missing a piece of information" me choque moins que "I have a piece of information missing"
Si c'est missing, je peux pas trop le have

2021-09-29 07:55 UTC, lixxday commented on tests/utils/rest_test.py
> +        with assert_num_queries(n_queries):
Je crois qu'il te manque un rebase :wink:

2021-09-29 08:01 UTC, xordoquy commented on src/pcapi/core/offerers/repository.py
> +def has_venue_missing_bank_information(offerer_id: int) -> bool:
sauf que `is_venue_missing_bank_information` porterai sur une venue et non un offerer.
`is_any_venue_missing_bank_information` ?

2021-09-29 08:05 UTC, xordoquy commented on src/pcapi/core/offerers/repository.py
> +def is_digital_venue_having_offers(offerer_id: int) -> bool:
S'il n'y a qu'un seul lieu numérique, on peut opter pour `has_digitial_venue_at_least_one_offer`

2021-09-29 10:28 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +    ).scalar()
On sérialisait auparavant les `BankInformation` de chaque lieu de la structure, et le front vérifiait s'il y avait un `None` dans la liste pour afficher un message.

2021-09-29 10:29 UTC, francois-seguin commented on tests/utils/rest_test.py
> +        with assert_num_queries(n_queries):
@lixxday Je n'ai pas compris ton commentaire.

2021-09-29 10:54 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +def has_venue_missing_bank_information(offerer_id: int) -> bool:
`has_venue_without_bank_information()` est l'heureux élu.

2021-09-29 11:06 UTC, francois-seguin commented on src/pcapi/core/offerers/repository.py
> +        .filter(offerers_models.Venue.bankInformation == None)
C'était ma 1e intention, mais cette syntaxe échoue. 
```
tests/core/offerers/test_repository.py:396: in test_complete_bank_info
    assert not has_venue_without_bank_information(offerer_id=offerer.id)
src/pcapi/core/offerers/repository.py:122: in has_venue_without_bank_information
    .filter(models.Venue.bankInformation.is_(None))
../../.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/sql/operators.py:670: in is_
    return self.operate(is_, other)
../../.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py:226: in operate
    return op(self.comparator, *other, **kwargs)
../../.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/sql/operators.py:1215: in is_
    return a.is_(b)
../../.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/sql/operators.py:670: in is_
    return self.operate(is_, other)
../../.virtualenvs/api/lib/python3.9/site-packages/sqlalchemy/sql/operators.py:230: in operate
    raise NotImplementedError(str(op))
E   NotImplementedError: <function is_ at 0x10c9144c0>
```

2021-09-29 11:12 UTC, francois-seguin commented on src/pcapi/core/users/models.py
> +            .scalar()
Je n'aimais pas la syntaxe originale, mais je ne fais pas consensus avec cette nouvelle -> je revert (en gardant les annotations de type quand même)

2021-09-29 11:35 UTC, xordoquy commented on src/pcapi/core/offerers/repository.py
> +        .filter(offerers_models.Venue.bankInformation == None)
C'est étrange, d'après [la doc](https://docs.sqlalchemy.org/en/13/orm/internals.html?highlight=is_#sqlalchemy.orm.RelationshipProperty.Comparator.is_) ça devrait marcher. A moins que ce ne soit à cause de la relation inverse ?

2021-09-29 11:55 UTC, lixxday commented on tests/utils/rest_test.py
> +        with assert_num_queries(n_queries):
Ah je dis ça parce que tu as nommé le commit `fixup! ...` comme si tu avais prévu de le squasher dans un autre commit

2021-09-29 11:57 UTC, dbaty commented
... et bien joué pour le nettoyage + le déplacement vers `core/offerers/repository` ! :)

2021-09-29 12:22 UTC, jeremieb-pass commented on src/pcapi/utils/rest.py
> +            status_code=400,
(détail) 404 plutôt, non ?

2021-09-29 12:52 UTC, francois-seguin commented on src/pcapi/utils/rest.py
> +            status_code=400,
Je ne l'avais pas corrigé pendant le déplacement ; c'est bien vu.

2021-09-29 13:02 UTC, francois-seguin commented on tests/utils/rest_test.py
> +        with assert_num_queries(n_queries):
Je ferai le squash avant le merge, car je préfère garder les commits atomiques de fixup lors des relectures.

2021-09-30 10:18 UTC, gael-boyenval requested changes
pour le moment je vois 1 problème, et une amélioration possible : 

- j'ai le flag hasVenueMissingBankInformation à true quand je n'ai qu'un lieu numérique (aucun lieu créé), et si je comprend bien, je n'attend pas de coordonnées bancaires pour ceux-ci (cf charlotte)

- aujourd'hui, des structures legacy peuvent avoir des informations bancaires auquel cas, on ne réclame pas d'informations bancaires sur les lieux, ne devrait-on pas prendre en compte cela quand on set hasVenueMissingBankInformation ? aujourd'hui c'est fait en front, mais ça ne me semble pas logique (c'est du métier), à discuter plus en détail...

2021-09-30 10:25 UTC, viconnex commented on src/pcapi/routes/pro/stocks.py
> +import pcapi.core.offerers.repository
`...as offerer_repository` ?

2021-09-30 10:32 UTC, viconnex commented on tests/routes/pro/get_offerer_test.py
>          create_bank_information(venue=venue_3, application_id=4)
est-ce qu'on peut créer d'autre bank_information sur la même Venue pour vérifier qu'on n'a pas de N+1 ?

2021-09-30 10:32 UTC, viconnex commented on tests/routes/pro/get_offerer_test.py
> +        with assert_num_queries(n_queries):
👏

2021-09-30 10:34 UTC, viconnex commented on tests/routes/pro/get_offerer_test.py
> +            + 1  # Offerer BankInformation
c'est quoi la ligne de code qui récupère la BankInformation ? Je vois pas non plus l'info dans la réponse

2021-10-01 08:58 UTC, francois-seguin commented
> pour le moment je vois 1 problème, et une amélioration possible :
> 
> * j'ai le flag hasVenueMissingBankInformation à true quand je n'ai qu'un lieu numérique (aucun lieu créé), et si je comprend bien, je n'attend pas de coordonnées bancaires pour ceux-ci (cf charlotte)

Oui, je modifie.

> * aujourd'hui, des structures legacy peuvent avoir des informations bancaires auquel cas, on ne réclame pas d'informations bancaires sur les lieux, ne devrait-on pas prendre en compte cela quand on set hasVenueMissingBankInformation ? aujourd'hui c'est fait en front, mais ça ne me semble pas logique (c'est du métier), à discuter plus en détail...

Je vérifie auprès des PO.

2021-11-03 16:26 UTC, francois-seguin commented
> pour le moment je vois 1 problème, et une amélioration possible :
> 
> * j'ai le flag hasVenueMissingBankInformation à true quand je n'ai qu'un lieu numérique (aucun lieu créé), et si je comprend bien, je n'attend pas de coordonnées bancaires pour ceux-ci (cf charlotte)
> * aujourd'hui, des structures legacy peuvent avoir des informations bancaires auquel cas, on ne réclame pas d'informations bancaires sur les lieux, ne devrait-on pas prendre en compte cela quand on set hasVenueMissingBankInformation ? aujourd'hui c'est fait en front, mais ça ne me semble pas logique (c'est du métier), à discuter plus en détail...

Je remets les règles métier:
Rappel des règles sur le logo d'avertissement de coordonnées bancaire manquantes côté Pro:
Les 2 logos d’avertissement sont à afficher dans le cas où : 

- Il n’y a pas de coordonnées bancaires enregistrées au niveau de la structure (pas de dossier en cours, en instruction ou validé) 
ET Il y a au moins un des lieux physiques qui n’a pas de coordonnées bancaires propres
cf https://passculture.atlassian.net/browse/PC-6667
- Si des offres numériques sont créées au niveau de la structure 
ET qu’il n’y a pas de coordonnées bancaires renseignées au niveau de la structure, alors afficher un logo d’avertissement. 
cf https://passculture.atlassian.net/browse/PC-7236

2021-11-09 10:29 UTC, gael-boyenval approved these changes

2021-11-09 12:17 UTC, merged